### ISSUE TITLE
irt75juz

### ISSUE THREAD

**Issue by Genio40921** [github/site-policy#1001]
**Please read our README.md and CONTRIBUTING.md files before creating an issue. If you are creating an issue to provide feedback about our Closed Policies, please note that we may not incorporate your feedback into our policies due to laws that limit our flexibility around those issues. If your feedback is not related to any of the questions below, feel free to delete the template questions and enter your comments in free form.**

**Comment by JamarMoultrie** [comment]
Cancel subscription

**Comment by VahidRafieiPour** [comment]
What happened to this VPN that I bought from you? I paid for my subscription

**Comment by VahidRafieiPour** [comment]
I don't have a preview, you just gave me a file to download so that I can think of Windows connection now, I want Windows and Android connection and username and password.

**Comment by lheng21** [comment]
im not the one who do this thing.

i don't have an idea either about what kind of this site
