### ISSUE TITLE
"How GitHub secures your information" broken link "security disclosures"

### ISSUE THREAD

**Issue by 0xpr03** [github/site-policy#114]
**Please read our README.md and CONTRIBUTING.md files before creating an issue. If you are creating an issue to provide feedback about our Closed Policies, please note that we may not incorporate your feedback into our policies due to laws that limit our flexibility around those issues. If your feedback is not related to any of the questions below, feel free to delete the template questions and enter your comments in free form.**

#### 1. What's the name of the policy?
github-privacy-statement

#### 2. Is this issue related to a specific section within one of our policies (e.g. the Terms of Service)? If so, please include a link to the section or subsection.
https://github.com/github/site-policy/blob/master/Policies/github-privacy-statement.md#how-github-secures-your-information

#### 5. Why do you think this section or language needs improvement?
The last sentence contains a hyperlink named "security disclosures". This link is broken.

**Comment by bluemazzoo** [comment]
Hi @0xpr03, thank you for your feedback! As [noted in the README](https://github.com/github/site-policy#whats-the-process), "Please note, links will not resolve in the rendering of the policies in this repository." Additional information can be found in this issue: https://github.com/github/site-policy/issues/82
