### ISSUE TITLE
Users and repository owners as third-party beneficiaries of inbound contributor license

### ISSUE THREAD

**Issue by advayDev1** [github/site-policy#129]
*I am not an attorney, and none of this is legal advice.*

Policies: Terms of Service ; and Corporate Terms of Service

Sections: https://github.com/github/site-policy/blob/master/Policies/github-corporate-terms-of-service.md#5-license-grant-to-other-users , https://github.com/github/site-policy/blob/master/Policies/github-corporate-terms-of-service.md#6-contributions-under-repository-license , https://github.com/github/site-policy/blob/master/Policies/github-terms-of-service.md#5-license-grant-to-other-users , https://github.com/github/site-policy/blob/master/Policies/github-terms-of-service.md#6-contributions-under-repository-license

Would GitHub consider making its users and repository owners explicit third-party beneficiaries of the license grants in sections 5 and 6, and allow them to enforce the 'inbound=outbound' conventional license independently of GitHub?  Why or why not?

**Comment by Lovegill5** [comment]
5 and 6

**Comment by Lovegill5** [comment]
https://github.com/github/site-policy/blob/master/Policies/github-corporate-terms-of-service.md#5-license-grant-to-other-users

**Comment by Lovegill5** [comment]
Policies/github-terms-of-service.md

**Comment by Lovegill5** [comment]
https://github.com/github/site-policy/blob/master/Policies/github-terms-of-service.md#5-license-grant-to-other-users

**Comment by advayDev1** [comment]
Hey GitHub any consideration of this?  Thanks!

**Comment by mlinksva** [comment]
Hi, apologies for overlooking this issue, thanks for the ping.

inbound=outbound is simply how most open source projects (those that don't use a CLA) work, and GitHub's terms affirm this. Our understanding is that the license grant provides an adequate defense if a contributor to a project argues that they did not intend to put the code under their license. GitHub does not enforce the license used by a project, rather the project's copyright holders (licensors) may.

I think that may answer your question, in which case it doesn't look like there is anything to add. If you're suggesting something novel, we'd like to see the concept demonstrated in open source practice before considering making it a default in our terms.
