### ISSUE TITLE
Allow disabling "remote: Create pull request for branch" message

### ISSUE THREAD

**Issue by kalinmiteli** [github/site-policy#130]
Hi, 
When we are trying to push our projects the following message appears on command line:
``` 
  remote: 
    remote: Create a pull request for 'feature/29574_basvuru_degerlendirme_widget' on GitHub by visiting:        
    remote:      https://github.com/ozguryazilimas/tekir4/pull/new/feature/29574_basvuru_degerlendirme_widget        
    remote: 
```
This message is very annoying (the GitHub frontend will also show a message to create a new merge request). How can this warning be disabled (or better: turn it off by default, as the same functionality is provided by the GitHub frontend).

Thanks and best regards.

**Comment by lee-dohm** [comment]
Thanks for reaching out.

This repository is for feedback on GitHub's site policy, including our Terms of Service, the Community Guidelines, various codes of conduct, and other legal or policy matters. If you have questions or suggestions about the GitHub service itself, please contact GitHub Support via our [contact form](https://github.com/contact) or via email at support@github.com.

**Comment by poetrydemon1982** [comment]
no worries my beloved online friends,😊

**Comment by dlbock** [comment]
@kalinmiteli did you get around to contacting GitHub Support about this issue?

**Comment by 0cjs** [comment]
Is there a way to turn this off, yet? Since this issue is what comes up when searching for a way to disable the message, it would be good to link here to the documentatioin that says how to do that (or the documentation that says you can't do that and the place to request this feature).

**Comment by lee-dohm** [comment]
Thanks for the feedback! Though I can't guarantee anything or share a timeline for this, I can tell you that it's been shared with the appropriate teams for consideration.

As stated above, this repository is for feedback on GitHub's site policy, including our Terms of Service, the Community Guidelines, various codes of conduct, and other legal or policy matters. If you have questions or suggestions about the GitHub service itself, please contact GitHub Support via our [contact form](https://github.com/contact)
