### ISSUE TITLE
Broken link to "adopt a license"

### ISSUE THREAD

**Issue by curran** [github/site-policy#136]
The [adopt a license](https://github.com/github/site-policy/blob/master/articles/adding-a-license-to-a-repository/#including-an-open-source-license-in-your-repository) link in section https://github.com/github/site-policy/blob/master/Policies/github-terms-of-service.md#5-license-grant-to-other-users is broken (when viewing from that URL).

Proposal: use an absolute URL so the link works no matter where the page is hosted.

I did submit a PR https://github.com/github/site-policy/pull/137

**Comment by mlinksva** [comment]
All of the links to other pages on help.github.com don't work when viewed in this repo. We don't currently have a fix for this; absolute links were suggested also in #119 but currently doesn't work with some of our internal tooling. The links work on help.github.com. Closing for now, but thanks for the report!

**Comment by curran** [comment]
Aha ok. Makes sense. Thanks!
