### ISSUE TITLE
CONTRIBUTING License Note

### ISSUE THREAD

**Issue by kemitchell** [github/site-policy#14]
From current `CONTRIBUTING.md`:

> Contributions to this project are dedicated to the public domain under the Creative Commons 0 terms and the final policies are licensed by GitHub under the Creative Commons Attribution 4.0 license.

Does this apply to folks like me, foisting CC0 on anything I send? The thought gives me an uncomfortable feeling. I think there are a couple reasons. Hopefully I can express them.

It's not inbound=outbound. Even looking past CC0's dedication, to the fallback license, the terms differ.

Having it in `CONTRIBUTING` feels like a gotcha, and therefore a bit like a grab. Like finding the [King's Shilling](https://en.wikipedia.org/wiki/King%27s_shilling) in your hand, so to speak.

I'm not sure it works under the current terms of service, in any event. Is that language in CONTRIBUTING a "separate agreement to license your contributions under different terms, such as a contributor license agreement"? Thinking like a lawyer, there's no signature or signature-substitute indicating agreement between GitHub and I for my contributions to the repo. Thinking like a coder, "contributor license agreement" means something like the Apache or old Eclipse forms. Not terms of service, or invoked on "hook" from terms of service.

It's a bit more work, but I'd actually prefer a note in CONTRIBUTING that the team can only take language verbatim under CC0-1.0, with a request to confirm dedication in PRs. That's a chore, but it would probably flip the feeling from "If I do things on that repo, GitHub takes under the license it wants." to "I'm being me by giving under CC0, because that's an excellent thing to do.".

**Comment by mlinksva** [comment]
Hi @kemitchell thanks for raising this. #29 switches the repo to inbound=outbound.
