### ISSUE TITLE
External Link To Swiss Safe Harbor Certification Is Broken

### ISSUE THREAD

**Issue by TheGreatKetchup** [github/site-policy#142]
In [global-privacy-practices.md/U.S.–Swiss Safe Harbor Framework](https://github.com/github/site-policy/blob/master/Policies/global-privacy-practices.md#usswiss-safe-harbor-framework) the link to Github's Swiss Safe Harbor certification does not work: 

https://safeharbor.export.gov/companyinfo.aspx?id=33260

This is also the case on the production page: https://help.github.com/articles/global-privacy-practices/

It would seem important that this link is fixed to prevent confusion.

**Comment by Quasic** [comment]
The site has some kind of problem. If you visit https://build.export.gov/main/safeharbor/swiss/index.asp and try to view the list of participants, you get the same message.

**Comment by bluemazzoo** [comment]
@TheGreatKetchup Thank you for your feedback! That policy has been updated and the link removed. Please see the [open pull request](https://github.com/github/site-policy/pull/156/files#diff-feebd5c10e3fa425360e07dd734644a8L40) for details. Closing this issue for now, but please feel free to reopen if you have any additional questions.
