### ISSUE TITLE
Typo in global-privacy-practices.md

### ISSUE THREAD

**Issue by TheGreatKetchup** [github/site-policy#143]
In file [global-privacy-practices.md](https://github.com/github/site-policy/blob/master/Policies/global-privacy-practices.md#privacy-shield-framework) under Recourse, Enforcement and Liability First Line:

"you can reach **our** with our {{ site.data.variables.contact.contact_privacy }} and"

Clearly the first "our" is meant to be "us".

----------
Also, I am assuming {{ site.data.variables.contact.contact_privacy }} is the correct text, but I am not sure if that is correct.

**Comment by bluemazzoo** [comment]
@TheGreatKetchup Thank you for your feedback! We've corrected the error in the [Global Privacy Practices](https://github.com/github/site-policy/pull/156) policy update. Closing this issue as addressed.
