### ISSUE TITLE
Update wording in light of change to private repos

### ISSUE THREAD

**Issue by nsqe** [github/site-policy#144]
#### 1. What's the name of the policy?
GitHub Terms of Service

#### 2. Is this issue related to a specific section within one of our policies (e.g. the Terms of Service)? If so, please include a link to the section or subsection.
https://help.github.com/articles/github-terms-of-service/#e-private-repositories

#### 4. Sometimes it's easier to just put your feedback text into an issue. If that's how you'd prefer to contribute, this is the section to do that.
Cool.

#### 5. Why do you think this section or language needs improvement?

Current language:

> Some Accounts, _such as paid Accounts,_ may have private repositories, which allow the User to control access to Content.

Emphasis mine.

Hi, guys!

**Comment by bluemazzoo** [comment]
@nsqe thank you for your feedback! We removed that language in our update to the Terms of Service pull request: https://github.com/github/site-policy/pull/155
