### ISSUE TITLE
Collection and Use of Data from GitHub Pages Sites

### ISSUE THREAD

**Issue by kemitchell** [github/site-policy#148]
Does the privacy policy offer explanation of what data GitHub collects about visitors to GitHub Pages sites?

Please forgive me if I'm looking right past it. Collection seems to address only "the website", which I take it means github.com.

**Comment by bluemazzoo** [comment]
@kemitchell Thanks for your feedback! We're updating our privacy statement to include more clarification around GitHub Pages data logging. Please see the [open pull request](https://github.com/github/site-policy/pull/153/files#diff-a79e515aa6f3f6bf03c75e9d51ab8932R141) for more details.

**Comment by bluemazzoo** [comment]
Closing this issue for now. Please feel free to reopen if you have any other questions on this subject.

**Comment by kemitchell** [comment]
Thanks for your answer and the link to the PR, @bluemazzoo!
