### ISSUE TITLE
A question about GitHub and Export Controls

### ISSUE THREAD

**Issue by Himself65** [github/site-policy#170]
#### 1. What's the name of the policy?

GitHub and Export Controls

#### 2. Is this issue related to a specific section within one of our policies (e.g. the Terms of Service)? If so, please include a link to the section or subsection.

```
GitHub.com, GitHub Enterprise Server, and the information you upload to either product may be subject to US export control laws, including U.S. Export Administration Regulations (the EAR).

Although we've provided the following information below for your convenience, it is ultimately your responsibility to ensure that your use of GitHub's products and services complies with all applicable laws and regulations, including US export control laws.
```

are `GitHub and Export Controls` rules will restrict the license of the repository itself?

**Comment by KOLANICH** [comment]
>are GitHub and Export Controls rules will restrict the license of the repository itself?

Not your attorney, not a legal advice, but definitely no. Licenses are fiends of copyright law. Export restrictions are fiends of other laws.

**Comment by mlinksva** [comment]
@Himself65 no, our terms (which include this policy) do not restrict the **copyright** license you may choose to use in your repository.

(Apologies for overlooking the question and thanks to @KOLANICH for the comment!)
