### ISSUE TITLE
Clarify that procedure for private repositories also applies to Student Developer Pack accounts

### ISSUE THREAD

**Issue by tkw1536** [github/site-policy#19]
In [Section D.8 Private Repositories](https://github.com/github/site-policy/blob/master/Policies/github-terms-of-service.md#8-private-repositories) of the _GitHub Terms of Service_ it says:

> Paid accounts may have private repositories, which allow the User to control access to Content. GitHub employees only access private repositories when access is required for security or maintenance or for support reasons, and then only with the consent of the repository owner.

This paragraph defines when GitHub staff may access private repositories **of paid accounts** under certain conditions. 
However, there are also non-paid accounts that can have private repositories, namely those given to students under the [Student Developer Pack](https://education.github.com/pack). It should be clarified that the protections also apply to those accounts.

**Comment by chengjinshengtaichanyejituan** [comment]
是的普遍性其实很多IT互联网的解决方案在国外都应该是共享知识的这对社会的共同发展起到很大作用，但在中国可能人均知识面问题，又或者个别龙头互联网企业，更或者个别性行为，把绝大部分的解决方案都从公有转变为私有，把更新部分方案隐蔽了起来，因此造成很多的信息不对称问题

**Comment by opu16** [comment]
www.facetimebd.tk

**Comment by Sergey-sirius** [comment]
ok

**Comment by nsqe** [comment]
@tkw1536 Thanks — you're totally right, more than just paid accounts can have private repositories, and of course the same rules apply to private repositories regardless of whether or not the account-holder has paid for them. We'll fix this. Thank you!

**Comment by evandrocoan** [comment]
> @chengjinshengtaichanyejituan 是的普遍性其实很多IT互联网的解决方案在国外都应该是共享知识的这对社会的共同发展起到很大作用，但在中国可能人均知识面问题，又或者个别龙头互联网企业，更或者个别性行为，把绝大部分的解决方案都从公有转变为私有，把更新部分方案隐蔽了起来，因此造成很多的信息不对称问题

**Google Translation:**
Is the universality of many IT Internet solutions in foreign countries should be shared knowledge of the common development of society play a significant role, but in China may be per capita knowledge problems, or individual leading Internet companies, or individual Sexual behavior, the vast majority of solutions from the public into a private, part of the program to conceal some of the update, resulting in a lot of information asymmetry

**Comment by QuantumDecay** [comment]
#1

**Comment by bluemazzoo** [comment]
@tkw1536 Changes have been made to incorporate your recommendations. Thanks for the contributions! 

Here's a link to the commit: https://github.com/github/site-policy/pull/1/commits/f3d54f64376b0edb97061628309e31d7609959e8
