### ISSUE TITLE
Japanese translation for github-terms-of-service

### ISSUE THREAD

**Issue by rxywm** [github/site-policy#210]
#### 1. What's the name of the policy?
[GitHub利用規約 - GitHub ヘルプ](https://help.github.com/ja/github/site-policy/github-terms-of-service#3-account-requirements) Japanese translation version of the [terms](../blob/master/Policies/github-terms-of-service.md)
#### 2. Is this issue related to a specific section within one of our policies (e.g. the Terms of Service)? If so, please include a link to the section or subsection.
Same as above
#### 3. Did you already open a pull request? If so, please include a link to the PR.
No, I can't find that is where located.
#### 4. Sometimes it's easier to just put your feedback text into an issue. If that's how you'd prefer to contribute, this is the section to do that.
[Section B, Article 3, item 1](https://help.github.com/en/github/site-policy/github-terms-of-service#3-account-requirements) Original english text is bellow:

```
You must be a human to create an Account. Accounts registered by "bots" or other automated methods are not permitted. We do permit machine accounts:
```

[Current japanese translation ToS](https://help.github.com/ja/github/site-policy/github-terms-of-service#3-account-requirements) is bellow:

```
「アカウント」を作成するのは人間でなければなりません。 「ボット」またはその他の自動化された手段で「アカウント」を登録することは許可されていません。 当社はコンピュータアカウントを許可していません:
```

`許可していません:` is meant `do not permit`

That should be:

```
「アカウント」を作成するのは人間でなければなりません。 「ボット」またはその他の自動化された手段で「アカウント」を登録することは許可されていません。 当社はコンピュータアカウントを許可しています:
```

`許可しています` is meant `do permit `

#### 5. Why do you think this section or language needs improvement?
Current translation are **opposite meaning**.

Diff: 
```
- 当社はコンピュータアカウントを許可していません:
+ 当社はコンピュータアカウントを許可しています:
```

「アカウント」を作成するのは人間でなければなりません。 「ボット」またはその他の自動化された手段で「アカウント」を登録することは許可されていません。 当社はコンピュータアカウントを許可していま~~せん~~**す**:

**Comment by mlinksva** [comment]
Thanks! Translations aren't currently maintained in this repo but we'll pass your correction to the team responsible and close this when it is implemented.

**Comment by mlinksva** [comment]
The translation at https://help.github.com/ja/github/site-policy/github-terms-of-service#3-account-requirements has been updated with this fix. Thanks!
