### ISSUE TITLE
How to set the English version after setting the Chinese display? 

### ISSUE THREAD

**Issue by hsiang168** [github/site-policy#293]

**Comment by hsiang168** [comment]
How to set the English version after setting the Chinese display? Because I really don't understand

**Comment by hsiang168** [comment]
How to display the display of the English version after setting it to the Chinese display, because the next option I can't find the language option!

資安好複雜🥶🥶🥶🥶

________________________________
寄件者: hsiang168 <notifications@github.com>
寄件日期: Tuesday, September 15, 2020 7:24:16 AM
收件者: github/site-policy <site-policy@noreply.github.com>
副本: hsiang168 <router909@outlook.com>; Your activity <your_activity@noreply.github.com>
主旨: Re: [github/site-policy] How to set the English version after setting the Chinese display? (#293)


How to set the English version after setting the Chinese display? Because I really don't understand

**Comment by lee-dohm** [comment]
Thanks for reaching out.

This repository is for feedback on GitHub's site policy, including our Terms of Service, the Community Guidelines, various codes of conduct, and other legal or policy matters. If you have questions or suggestions about the GitHub service itself, please contact GitHub Support via our [support site](https://support.github.com/contact).

**Comment by hsiang168** [comment]
Yeh
Even every嗎？請確認本人發出與否，謝謝

**Comment by hsiang168** [comment]
Dudu

Even every嗎？請確認本人發出與否，謝謝
