### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Jswinney117** [github/site-policy#307]
https://github.com/pyca/cryptography/pull/5483

**Comment by th3b0x** [comment]
@Jswinney117 your comment was made without context.  What is the specific issue in relation to the pull request referenced in your post?

**Comment by futuregifts** [comment]
> @Jswinney117 your comment was made without context.  What is the specific issue in relation to the pull request referenced in your post?

Blocked out of sites I need for business, has to do with I'm I believe
