### ISSUE TITLE
The README file in this repo has some bad links - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [github/site-policy#326]
The README file in this repo has some bad links - [404:NotFound]

Status code [404:NotFound] - Link: https://github.com/github/site-policy/blob/main/github/site-policy/github-privacy-statement
Status code [404:NotFound] - Link: https://github.com/github/site-policy/blob/main/github/site-policy/github-terms-of-service#q-changes-to-these-terms

I think I can work out what they should be and will submit a PR very shortly…

This was found by an new experimental hobby project that I have just created: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
If this has been in any way helpful then please consider giving the above Repo a Star.

**Comment by Fate-Zombie** [comment]
> The README file in this repo has some bad links - [404:NotFound]
> 
> 
> 
> Status code [404:NotFound] - Link: https://github.com/github/site-policy/blob/main/github/site-policy/github-privacy-statement
> 
> Status code [404:NotFound] - Link: https://github.com/github/site-policy/blob/main/github/site-policy/github-terms-of-service#q-changes-to-these-terms
> 
> 
> 
> I think I can work out what they should be and will submit a PR very shortly…
> 
> 
> 
> This was found by an new experimental hobby project that I have just created: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
> 
> If this has been in any way helpful then please consider giving the above Repo a Star.
> 
>

**Comment by mlinksva** [comment]
Fixed by #327
