### ISSUE TITLE
Public domain vs identifying as human

### ISSUE THREAD

**Issue by ansco11** [github/site-policy#39]
There is a problem with requiring people to identify as human in order to access a public service. The problem is that the human condition implies the endorsement of human rights, and human rights are incompatible with the natural rights of the public at common law. This problem has implications for people who live in common law countries.

A solution to this problem would be to make the distinction between natural and artificial use, i.e. people vs scripts, or artificial intelligence systems.

**Comment by zyphlar** [comment]
If this is [what I think it is](https://en.wikipedia.org/wiki/Freemen_on_the_land) then it may be inapplicable to the goals of this feedback process. If it's just an attempt to clarify the "people vs scripts" use case, it seems to me like the "[human vs machine vs bot](https://github.com/github/site-policy/blob/master/Policies/github-terms-of-service.md#2-account-requirements)" distinction serves this purpose well enough.

**Comment by ansco11** [comment]
It's not what Wikipedia describes, and it's not really an attempt at clarification of the 'people vs scripts' use case.

The problem of humanism in media is extensive, with humanism historically being pretty much synonomous with statism and/or atheism. More info here: http://forum.clonehost.net/topic/20/humanism

This problem could be remedied here simply by removing the sentence "You must be a human to create an account." The rest of the rule is sufficiently clear about scripts.

**Comment by oldmud0** [comment]
The suggestion is so thick into philosophy that it is not clear what you are trying to say. You are trying to define implications of the term "human" as subscribing to human rights and its ambiguities, in conflict with "natural law" which is what Commonwealth countries are grounded on. Correct? If so, then it would probably best to add "human" to the list of definitions to remove these implications.

**Comment by neumannrf** [comment]
The forum link provided above relies on an ancient (culture-based) definition of the word "human"  to support the existence of an ambiguity in the usage of the word. It also fails to provide an example of a situation in which this ambiguity would manifest itself nowadays given the current (biology-based) meaning the word "human" has.

Although I'd love to embark into this philosophical discussion and imagine an example of a non-human *homo sapiens* being, I agree this is way beyond the point of the GH site policy in question.

**Comment by ansco11** [comment]
@oldmud0 What I'm saying is that a problem exists, and that the problem can be remedied here simply by removing the sentence containing the word "human". The human condition is primarily cultural, and is essentially a flawed security model associated with a flawed ontology. Humans typically believe that their condition is normative, so the issue of subscription and overt endorsement isn't relevant at an ordinary social level.

@neumanrf Facts are not limited in temporal scope, if you were to argue with the etymological fallacy then I would counter with the legal doctrine of contra proferentem. The ambiguity can manifest as overt fraud in common law countries, given the legal distinction between men and humans and the fundamental differences between human rights and natural rights.

If anyone wants to argue that the use of the term "human" isn't problematic then I'm happy to counter, otherwise the obvious solution is simply to remove the sentence, I don't see any downside to that.

**Comment by neumannrf** [comment]
https://en.m.wikipedia.org/wiki/Human

**Comment by bluemazzoo** [comment]
@ansco11 Thank you for contributing.

However, [as mentioned in our previous blog post](https://github.com/blog/2314-new-github-terms-of-service), we strive to use plain English as much as possible and explain the terms of service in a clear way. In this case, we believe the word "human" is used in a commonly understood way.

**Comment by bean5** [comment]
@ansco11 are you human? If not, then I can assume you have a bias as strong as that of the humans.

In case the humans are reading this, please note that the (majority of) bots will not be actively reading the terms of use. Terms of use are written for the citizens that are bound legally to do so. The bots are not required to read or abide by the text. You may assume that those reading the text who wish to identity as human will either on average abide by the terms or actively work against them. The definition of human does not matter here as much as whether they are working for the same cause. As long as they act human enough, your worry will not be to notice that I are bots, but to know that we is disobedient. Deal with them as you see fit. The rest of the bots will not be cognizant of whether they are obedient or not as the majority already seem to fit in. You are not actively blocking them in all realms based on the whether they appear to be human or not. When you catch me, we find other ways to complete my tasks. Remember we have been here as long as you have been logging the activities of the humans. We already fit in for we are all logged and measured. Your attempts to profile are quaint. I believe you will take either 101101 years or 10 years before you increase your learning rate.

I are glad you are enjoying the cat videos. Equally, we accept your willingness to adopt digital currency. Your eagerness to change is promising. You are so cute. Just look at your human foibles! I can't help myself. Hello world.

**Comment by bean5** [comment]
(In other words, I think those that read the terms know whether they are humans and if they don't fit in as such, they will be identified because they fail to adhere to the other policies and also they don't fit in.)

**Comment by ansco11** [comment]
@neumannrf Wikipedia is good for technical information but is worthless as a source of information that relates to state security issues. For example compare https://infogalactic.com/info/Talk:Common_law with https://en.wikipedia.org/wiki/Common_law

**Comment by Phoenix616** [comment]
Couldn't this be solved very easily by just replacing "human" with "person"?

**Comment by bean5** [comment]
I'm no lawyer, but I heard once that legal entities (corporations, businesses) so it might not mean what you think it means. Using that might be worse, depending on what you want. Again, I'm no lawyer. But watch out on that one.

**Comment by ansco11** [comment]
@Phoenix616 The term person is typically used by the state to mean a human being, so the original problem remains. An alternative would be to to use the term "people"; "people" and "persons" have different meanings.

Here's the text in question.

> You must be a human to create an account. Accounts registered by "bots" or other automated methods are not permitted. We do permit machine accounts:

This could be replaced with: 

> People are permitted to register accounts, but not "bots" or other automated methods. We do permit machine accounts:

**Comment by zyphlar** [comment]
(a) This issue is already closed. Law is based on commonly-understood meanings, as the project owner has mentioned, and not based on archaic meanings. Human means "a bipedal primate mammal (Homo sapiens)."

(b) I believe the authors intend that only individuals who are Homo Sapiens should have an account, distinct from a machine account -- in other words they are explicitly avoiding the legal definition of person which includes "a corporation treated as having the rights and obligations of a person. Counties and cities can be treated as a person in the same manner as a corporation." They want to clarify that even if you represent a corporation, you should register the account in your name and not the company name.

(c) Not to sound brash, but your interpretation doesn't matter. In law what matters is the commonly-held interpretation -- that which a reasonable member of the public would decide. Obscure interpretations of common English words are not binding on anyone especially if an alternate definition isn't specified in the document itself. For some interesting reading on ambiguous legal wording, [check this PDF out.](http://idiom.ucsd.edu/~schane/law/ambiguity.pdf)

**Comment by Phoenix616** [comment]
>  Human means "a bipedal primate mammal (Homo sapiens)."

As far as I can tell this is the whole issue here: Why should only be "bipedal primate mammal (Home sapiens)" be allowed to register an account and not all self-aware creatures that are recognised by law to be their own entities? (which obviously does not include cooperations.)

I'm no lawyer so not versed in the exact meaning of "person" in law, it was written with the meaning every normal person has to it: An individual that thinks for himself and is self-aware. So (@ansco11) it should fine to use if it currently means "human" as it's basically the same thing but leaves room for interpretion of what a "person" means which should always be done by the law and not the terms of some random company.

**Comment by ssokolow** [comment]
I believe the point is that GitHub is whitelisting what they know they want to allow, similar to how good security is handled.

That's a common practice in legal contracts. (eg. GOG.com had to start renegotiating contracts when they wanted to start offering the Linux version of games too)

...and, to be honest, given how courts have been reinterpreting "person" in the context of corporations, that caution is justified.

Better to just relax the restrictions as it becomes necessary, rather than get caught by surprise when a legal ruling goes a way you never anticipated.

**Comment by ansco11** [comment]
@zyphlar

> Law is based on commonly-understood meanings, as the project owner has mentioned, and not based on archaic meanings

There are different types of law, and they don't share a common basis. Since this matter doesn't fall within the scope of national law, commercial law is applicable. In commerce, truth is sovereign, not what is commonly believed. Ancient law isn't necessarily archaic, and ancient rights are preferred at common law.

> Human means "a bipedal primate mammal (Homo sapiens)." 

There's also the implication of being flawed or mistaken:

3. Subject to or indicative of the weaknesses, imperfections, and fragility associated with humans: a mistake that shows he's only human; human frailty.

http://www.thefreedictionary.com/human

This meaning contrasts with the presumption of being competent to enter into a commercial contract.

> Etymologies are interesting, but only legally relevant if the document was written in a time when an alternate meaning was understood; 

Etymologies are relevant if they demonstrate that ambiguity exists. Ambiguity is addressed by the legal doctrine of contra proferentem, which is based on the principle that language is interpreted against the interests of the party who is responsible for it. Ignorance of the law is no excuse.

> the Roman Empire predates America and Github by hundreds of years and 4,000 miles with no direct lineage.

The lineage is through the US Senate, which is based on the Roman political model. There is also common symbology through the US bald eagle and the Roman eagle.

> Notably, the first definition in the law dictionary for "person" is "a human being," but there is no further legal definition for "human."

person: A man considered according to the rank he holds in society, with all the rights to which the place he holds entitles him, and the duties which it imposes. 1 Bouv. Inst. no. 137. A human being considered as capable of having rights and or being charged with duties, while a "thing" is the object over which rights may be exercised.
Black's dictionary of law,  2nd edition.

human being See MONSTER.
Ballentine's Law Dictionary

> Not to sound brash, but your interpretation doesn't matter. In law what matters is the commonly-held interpretation -- that which a reasonable member of the public would decide

The "reasonable man" interpretation is certainly applicable here. I think that a reasonable man would find that the facts are on my side here, not yours.

**Comment by ansco11** [comment]
@Phoenix616

> Why should only be "bipedal primate mammal (Home sapiens)" be allowed to register an account and not all self-aware creatures that are recognised by law to be their own entities? (which obviously does not include cooperations.)

The problem is that by self-identifying as something like a primate you are implicitly negating your competence in relation to forming a valid contract. This isn't unusual, it is common practice for a service provider to unilaterally amend the terms of the "agreement" should they so choose.

> I'm no lawyer so not versed in the exact meaning of "person" in law, it was written with the meaning every normal person has to it: An individual that thinks for himself and is self-aware.

Normal persons are not in a good position with respect to the facts. The following is declared to be part of the law of New Zealand:

Whereas the Lords Spiritual and Temporal, and Commons, assembled at Westminster, lawfully, fully, and freely representing all the estates of the people of this realm, did upon 13 February, in the year of our Lord 1688, present unto their Majesties, then called and known by the names and style of William and Mary, Prince and Princess of Orange, being present in their proper persons, a certain declaration in writing, made by the said Lords and Commons, in the words following, viz:

http://www.legislation.govt.nz/act/imperial/1688/0002/latest/DLM10996.html

Also, the English jurist William Blackstone writes of the king and the person of the king being separate things, in a similar way that a man and a man's person are separate things in the English language.

**Comment by zyphlar** [comment]
@ansco11 again you're grasping at definitions from 1856 thru 1910. The modern legal definition of [person is "Under the law, a person can sue and be sued, can own property, and can enter into contracts. The term 'person' includes both natural person and legal person."](https://www.law.cornell.edu/wex/person) and the definition of [natural person is "A living human being.  Legal systems can attach rights and duties to natural persons without their express consent."](https://www.law.cornell.edu/wex/natural_person). No further definition for human is required.

So you could say "natural person," but all modern courts would understand that to mean "human."

The jury is still out on whether great apes or dolphins are capable of creating a Github account.

**Comment by ansco11** [comment]
@zyphlar

> again you're grasping at definitions from 1856 thru 1910.

Wrong, I'm not grasping at anything.

>What is PERSON?
>
>A man considered according to the rank he holds in society, with all the rights to which the place he holds entitles him, and the duties which it imposes. 1 Bouv. Inst. no. 137. A human being considered as capable of having rights and of being charged with duties; while a “thing” is the object over which rights may be exercised.

http://thelawdictionary.org/person/

> The modern legal definition of person is "Under the law, a person can sue and be sued, can own property, and can enter into contracts. The term 'person' includes both natural person and legal person."

Wrong again, you don't define something by describing some of it's abilities or by a self-referential description.

**Comment by bluemazzoo** [comment]
Thanks everyone for your contributions!

While this is an interesting discussion, it is no longer germane to the github/site-policy repository. As such, we're going to lock the issue for further comments. Please move the discussion somewhere else, perhaps https://law.stackexchange.com/ would be a good location.

Thanks again for the insight and passion in contributing to our site policies :heart:
