### ISSUE TITLE
read my email?

### ISSUE THREAD

**Issue by Haleymiranda79** [github/site-policy#399]
Why does Github need to act on my behalf for me to join forums? You need to read my email? That's so sketchy. Have I been hacked? Yes, I should have put this somewhere  else. I'm  need guidance and you want to read my email? I hope that was fake.

**Comment by pcihon** [comment]
Hi @Haleymiranda79. Please see our [guidelines](https://github.com/github/site-policy/blob/main/CONTRIBUTING.md) on how to contribute to the site-policies in this repo. For other matters, you can find assistance at https://support.github.com/
