### ISSUE TITLE
The word, "compromises," is not quite clear in this sentence and should be refined.

### ISSUE THREAD

**Issue by vollmera** [github/site-policy#408]
The word, "compromises," is not quite clear in this sentence and should be refined.

_Originally posted by @sickcodes in https://github.com/github/site-policy/pull/406#discussion_r640036311_

**Comment by artursavin86** [comment]
Асистемность

**Comment by artursavin86** [comment]
``

**Comment by chole22** [comment]
![image](https://user-images.githubusercontent.com/57058450/124714809-a061d380-ded8-11eb-8e2c-67fae27e5235.jpeg)

**Comment by chasemooney86** [comment]
I was more than harassed and Abuse through these actions who do I reach out too….

**Comment by chasemooney86** [comment]
Not just me either but i need someone who can share she answers with me honestly

**Comment by artursavin86** [comment]
[![image](https://user-images.githubusercontent.com/85589250/122852142-56a2b600-d33a-11eb-9ef2-435b62895d64.jpeg)](#406)

**Comment by vollmera** [comment]
As we looked into this issue, we realized our Acceptable Use Policies account for the prohibited uses of Pages. So we [updated](https://github.com/github/site-policy/pull/478/files) the Pages terms' [prohibited uses](https://docs.github.com/en/github/site-policy/github-terms-for-additional-products-and-features#pages) to note that
>GitHub Pages may not be used in violation of the Agreement, the GitHub [Acceptable Use Policies](/github/site-policy/github-acceptable-use-policies), or the GitHub Pages service limitations set forth in the [Pages documentation](/pages/getting-started-with-github-pages/about-github-pages#guidelines-for-using-github-pages).

and also updated the [Pages documentation](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#guidelines-for-using-github-pages) to note some examples.
