### ISSUE TITLE
Clarify Code of Conduct enforcement section

### ISSUE THREAD

**Issue by CaraJDonnelly** [github/site-policy#41]
#### 1. What's the name of the policy?

code_of_conduct.md->Contributor Covenant Code of Conduct->Enforcement

#### 2. Is this issue related to a specific section within one of our policies (e.g. the Terms of Service)? If so, please include a link to the section or subsection.

https://github.com/github/site-policy/blob/master/CODE_OF_CONDUCT.md#enforcement

#### 3. Did you already open a pull request? If so, please include a link to the PR.

No; issue is too wide in scope for a pull request.

#### 5. Why do you think this section or language needs improvement?

Reporting unacceptable behaviour is a critical user journey and should be made as easy as possible.  Providing an email address (i.e. providing no integration with any of GitHub's interfaces) undermines the importance of this item.

*  This enforcement section should have a link to an open issue against the GitHub interfaces to improve the user experience of people reporting unacceptable behaviour beyond "Email us (template not provided), and someone should read it and may choose to do something.".  Since each project maintainer is expected to manage their own code of conduct a way of reporting harassing actions to each project maintainer seems key.  Please add such a link to such a (placeholder) issue.

*  This enforcement section states that "Further details of specific enforcement policies may be posted separately." but does not state where they might be stated.  This undermines the authoritative nature of this documentation.  Please provide where those further details should be stated, or state that those details, or a link to those details, will be added to this document at a later time.

**Comment by lee-dohm** [comment]
Are you asking for clarification of this repository's [Code of Conduct](https://github.com/github/site-policy/blob/master/CODE_OF_CONDUCT.md)? Or is your question in relation to GitHub's site policies?

**Comment by CaraJDonnelly** [comment]
I see -- I had not understood that only text in policies/ were under review as part of this process.  My apologies.   I withdraw my above request for clarification; thank you for your time.

I note that there is a relative link in

https://github.com/github/site-policy/blob/master/Policies/github-community-guidelines.md

which ought lead to

https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/

but leads instead to

(404) https://github.com/github/site-policy/blob/master/articles/adding-a-code-of-conduct-to-your-project

.  I'll submit a pull request to make this an absolute link.

**Comment by CaraJDonnelly** [comment]
Actually, I won't submit a pull request, just in case this would count as moonlighting.  I note the above link is broken, and leave it at that.

**Comment by bluemazzoo** [comment]
@CaraJDonnelly Thank you for contributing!

Unfortunately, since all of the site policies are direct copies from our [GitHubHelp page](https://help.github.com/categories/site-policy/), they contain the same local links as the live policies, leading to broken links in the site-policy repo. Sorry for the inconvenience.
