### ISSUE TITLE
Sofomio

### ISSUE THREAD

**Issue by Piojoso27** [github/site-policy#428]
**Please read our README.md and CONTRIBUTING.md files before creating an issue. If you are creating an issue to provide feedback about our Closed Policies, please note that we may not incorporate your feedback into our policies due to laws that limit our flexibility around those issues. If your feedback is not related to any of the questions below, feel free to delete the template questions and enter your comments in free form.**

**Comment by Piojoso27** [comment]
Esperemos sea de alluda su apollo

**Comment by Piojoso27** [comment]
Gracias

**Comment by pcihon** [comment]
Hi @Piojoso27, I'm closing this issue as off-topic. If you're interested in providing feedback on GitHub's site policies, please complete the issue template. Gracias.

**Comment by Piojoso27** [comment]
Necesito que mi celular se conectecte a la red telcel como estaba solo
empezo a azer eso ya intente bariaa cosas y no puedo sera que ud me ayuden
