### ISSUE TITLE
`Array.prototype.sort` was already made stable in ECMAScript 2019 (see two paragraphs above). The change in https://github.com/tc39/ecma262/pull/1585 made `Array.prototype.sort` more precise, reducing the amount of cases that result in an implementation-defined sort order.

### ISSUE THREAD

**Issue by MRGRAY0000** [github/site-policy#439]
`Array.prototype.sort` was already made stable in ECMAScript 2019 (see two paragraphs above). The change in https://github.com/tc39/ecma262/pull/1585 made `Array.prototype.sort` more precise, reducing the amount of cases that result in an implementation-defined sort order.

__Originally posted by @mathiasbynens in https://github.com/tc39/ecma262/pull/2342__

**Comment by KOLANICH** [comment]
Some peolle use extremily old browsers...

**Comment by pcihon** [comment]
Hi @MRGRAY0000, I'm closing this as off topic. Please see our [Contributing.md](https://github.com/github/site-policy/blob/main/CONTRIBUTING.md) for the types of feedback we're looking for on our Site Policies in this repo.
