### ISSUE TITLE
I haven't touched the tests either - again, I want to be sure you're OK with the direction first.

### ISSUE THREAD

**Issue by MRGRAY0000** [github/site-policy#440]
I haven't touched the tests either - again, I want to be sure you're OK with the direction first.

__Originally posted by @peterhoeg in https://github.com/DamienCassou/vdirel/pull/18#issuecomment-803846493__

**Comment by pcihon** [comment]
Hi @MRGRAY0000, I'm closing this as off topic. Please see our [Contributing.md](https://github.com/github/site-policy/blob/main/CONTRIBUTING.md) for the types of feedback we're looking for on our Site Policies in this repo.
