### ISSUE TITLE
**23999[23000$]()_**

### ISSUE THREAD

**Issue by nelsondani** [github/site-policy#442]
**23999[23000$]()_**

__Originally posted by @nelsondani in https://github.com/xAgustin93/calculadora-apple/issues/1__

**Comment by nelsondani** [comment]
-  Her way @nnelsondani

**Comment by Vut11** [comment]
สราวุธม่วงเอี่ยมโอนเงิน4320529762ไทย

**Comment by cannujBarfu0negjiz** [comment]
> **2399923000 $_**
> 
> **Publicado originalmente por @nelsondaniinxAgustin93[/calculadora-apple#1](https://github.com/xAgustin93/calculadora-apple/issues/1)**

**Comment by Vut11** [comment]
โอนเข้าบันชีธนาคารไทยพาณิชย์4320529762 SARAWUT MUANGAIAM

**Comment by pcihon** [comment]
Closing as off topic
