### ISSUE TITLE
I used some ham-handed instrumentation to see where the stack was growing.

### ISSUE THREAD

**Issue by osamao3** [github/site-policy#464]
I used some ham-handed instrumentation to see where the stack was growing.

The extreme case (running `bazel-out/k8-fastbuild/bin/absl/debugging/symbolize_test --gtest_filter=Symbolize\*Stack*:\*Cache\*`)

is due to the `snprintf` call in `ReadAddrMap` (which uses a lot of stack)

In the normal (all gtests case), by the time the stack consumption tests run, `FindSymbolInCache` succeeds and almost none of `Symbolizer::GetSymbol` runs as a result. When the tests are run in isolation, `FindSymbolInCache` returns null and the rest of `GetSymbol` runs.

__Originally posted by @AlexK-BD in https://github.com/abseil/abseil-cpp/issues/1012#issuecomment-912824883__

**Comment by pcihon** [comment]
👋 @osamao3, thanks for opening the issue. I'm closing this, as it's off topic. If you'd like to suggest changes to GitHub's Site Policies, please read our [contributing guidelines](https://github.com/github/site-policy/blob/main/CONTRIBUTING.md).
