### ISSUE TITLE
Improve D.6 to make it more flexible

### ISSUE THREAD

**Issue by KOLANICH** [github/site-policy#466]
#### 1. What's the name of the policy?

ToS

#### 2. Is this issue related to a specific section within one of our policies (e.g. the Terms of Service)? If so, please include a link to the section or subsection.

>6. Contributions Under Repository License

>Whenever you add Content to a repository containing notice of a license, you license that Content under the same terms, and you agree that you have the right to license that Content under those terms.

#### 3. Did you already open a pull request? If so, please include a link to the PR in the [GitHub Docs repo](https://github.com/github/docs).

No.

#### 5. Why do you think this section or language needs improvement?

The current text has multiple issues.

1. A repo can contain different files under different licenses. In this case it is ambigious which one is applies.

2. It is unfair to mandate a user to license the content under the same license. I.e. I may want to add some content under Unlicense into a repo under AGPL. It doesn't necessarily mean that the content under Unlicense is infected with AGPL and must be under it. I.e. it may be a helper script not linking or including any AGPLed code.

So, that part needs refactoring.

1. Rather than mandate licensing under the same license, just say that the default license for the content is the default license of the repo being contributed to.
2. The defaults are in action if the content is not explicitly licensed under another license.
3. How can content be explicitly licensed under other licenses? By multiple means, such as license headers, simple text in ReadMe stating that, and even machine-readable ways like SPDX headers,  `reuse`, `Machine-readable debian/copyright file` and other ones.
4. This must only apply to
    a. repos that once were public
    b. private repos, that have been used to send a PR to someone

**Comment by bapakahh** [comment]
close please

**Comment by Moi0** [comment]
<3

**Comment by margaret-tucker** [comment]
Thank you for reaching out. This TOS provision is trying to capture the flexible inbound == outbound license scheme followed by most projects. The nuanced issues you describe are covered by "a license" rather than a particular file and the clarification at the end of the provision that contributor and maintainer can agree to other terms. This would include using another license in the submission.
