### ISSUE TITLE
nonsence

### ISSUE THREAD

**Issue by chriscamacho** [github/site-policy#47]
Not written in understandable English, and basically meaningless, where is the contract with a signature by *both* parties? 
 imposing even by consultation terms is onerous and entirely without merit or morals... 

**Please read our README.md and CONTRIBUTING.md files before creating an issue. If you are creating an issue to provide feedback about our Closed Policies, please note that we may not incorporate your feedback into our policies due to laws that limit our flexibility around those issues. If your feedback is not related to any of the questions below, feel free to delete the template questions and enter your comments in free form.**

**Comment by TAGC** [comment]
"Not written in understandable English"

_looks at issue title_

**Comment by KrakenZ** [comment]
How ironic.

**Comment by bluemazzoo** [comment]
Thank you for contributing. If you have any other recommendations, feel free to reopen this issue or open a PR.

**Comment by lee-dohm** [comment]
@TAGC your comment was deleted as a violation of the [Site Policy Code of Conduct](https://github.com/github/site-policy/blob/master/CODE_OF_CONDUCT.md) as it was insulting or derogatory. You may consider this an official warning.

**Comment by chriscamacho** [comment]
it was in no way intended to be derogatory nor for that matter insulting, this area of contract law is a very grey area and poses a serious issue to assumed terms and conditions.

**Comment by ssokolow** [comment]
@chriscamacho Now *that* I can certainly agree with.

For example, as I understand it, that "unequal bargaining power" aspect [played a role](http://www.michaelgeist.ca/2017/06/supreme-court-rules-facebook-cant-contract-b-c-privacy-law/) in the recent Supreme Court of Canadadecision to overrule the forum selection clause in Facebook's Terms of Service because it would prevent a Facebook user from filing suit for violation of British Columbia privacy laws.

**Comment by lee-dohm** [comment]
@chriscamacho [my comment](https://github.com/github/site-policy/issues/47#issuecomment-315810782) was not directed at your issue but at the comment that I deleted:

<img width="498" alt="screen shot 2017-07-18 at 12 58 34 pm" src="https://user-images.githubusercontent.com/1038121/28336960-d56d45ec-6bb8-11e7-9943-8f989b7ec328.png">

I apologize for the confusion.
