### ISSUE TITLE
![image](https://user-images.githubusercontent.com/6750723/137076626-9d786dc9-ca7c-4fe7-9435-454b5a0c799b.jpeg)

### ISSUE THREAD

**Issue by 966563058015** [github/site-policy#473]
![image](https://user-images.githubusercontent.com/6750723/137076626-9d786dc9-ca7c-4fe7-9435-454b5a0c799b.jpeg)

__Originally posted by @966563058015 in https://github.com/github/site-policy/pull/121#issuecomment-941953820__

**Comment by pcihon** [comment]
Hi @966563058015, I'm closing this as off topic. Please see our [Contributing.md](https://github.com/github/site-policy/blob/main/CONTRIBUTING.md) for the types of feedback we're looking for on our Site Policies in this repo.
