### ISSUE TITLE
Change "Responsible" Vulnerability Disclosure policy to "Coordinated" Vulnerability Disclosure

### ISSUE THREAD

**Issue by JLLeitschuh** [github/site-policy#477]
#### 1. What's the name of the policy?

Responsible Disclosure of Security Vulnerabilities

#### 2. Is this issue related to a specific section within one of our policies (e.g. the Terms of Service)? If so, please include a link to the section or subsection.

https://docs.github.com/en/github/site-policy/responsible-disclosure-of-security-vulnerabilities#article-contents

#### 3. Did you already open a pull request? If so, please include a link to the PR in the [GitHub Docs repo](https://github.com/github/docs).

 - https://github.com/github/docs/pull/11451

#### 4. Sometimes it's easier to just put your feedback text into an issue. If that's how you'd prefer to contribute, this is the section to do that.

The name of the policy should be changed from "Responsible Disclosure of Security Vulnerabilities" to "Coordinated Disclosure of Security Vulnerabilities".

#### 5. Why do you think this section or language needs improvement?

For lots of the discussion and points here I'll be referencing this article [Coordinated Vulnerability Disclosure: Bringing Balance to the Force](https://docs.microsoft.com/en-us/archive/blogs/ecostrat/coordinated-vulnerability-disclosure-bringing-balance-to-the-force) by [Katie Moussouris](https://twitter.com/k8em0) from 2010.

"Responsible" implies a set of ethics and morals are involved in vulnerability disclosure. "responsible" is also very subjective. From the perspective of the security researcher, the company (in this case GitHub) may be the "irresponsible" party for releasing the vulnerable code without adequate testing. From the perspective of the company, in this case GitHub, the researcher may be "irresponsible" if they choose to go public with a vulnerability before the vulnerability is fully patched and shipped to customer. As such, much of the industry has moved away from the term "Responsible" to the term "Coordinated".

> Responsible Disclosure should be deprecated in favor of something focused on getting the job done, which is to improve security and to protect users and systems.

Additionally, Coordinated Vulnerability Disclosure (CVD) has been the norm at Microsoft for 11 years. GitHub should similarly match the language around vulnerability disclosure that Microsoft has.

Also, I'm regularly working with the GitHub Security Lab and they use a Coordinated Disclosure Policy. It would be nice if this policy were consistent across GitHub.

 - https://docs.github.com/en/code-security/security-advisories/about-coordinated-disclosure-of-security-vulnerabilities
 - https://securitylab.github.com/advisories/#policy
 
 ---
 
 While this is being addressed. I believe the following change should also be made here:

> https://bounty.github.com/#legal_safe_harbor

Currently:

> We want you to responsibly disclose through our bug bounty program, and don’t want researchers put in fear of legal consequences because of their good faith attempts to comply with our bug bounty policy. We cannot bind any third party, so do not assume this protection extends to any third party. If in doubt, ask us before engaging in any specific action you think might go outside the bounds of our policy.

Should be changed to:

> We want you to coordinate disclosure through our bug bounty program, and don’t want researchers put in fear of legal consequences because of their good faith attempts to comply with our bug bounty policy. We cannot bind any third party, so do not assume this protection extends to any third party. If in doubt, ask us before engaging in any specific action you think might go outside the bounds of our policy.

**Comment by vollmera** [comment]
@JLLeitschuh - thanks so much for opening this issue and the PR ✨ 

>The name of the policy should be changed from "Responsible Disclosure of Security Vulnerabilities" to "Coordinated Disclosure of Security Vulnerabilities".

💯 - Apologies for not getting to this yet - it's on deck for next week.

**Comment by bapakahh** [comment]
https://docs.github.com/en/github/site-policy/responsible-disclosure-of-security-vulnerabilities#article-contents .... close please

**Comment by vollmera** [comment]
@JLLeitschuh I pushed https://github.com/github/docs/pull/11451/commits/ec06da126b9b9271d518dc4c67b557d4cdf08203 to `~responsible~ **coordinated**` in one more spot and added [Bug Bounty Program - Legal Safe Harbor](https://docs.github.com/github/site-policy/github-bug-bounty-program-legal-safe-harbor) to your PR.

https://bounty.github.com/#legal_safe_harbor is maintained separately. We'll update the site-policy docs in the meantime.

**Comment by vollmera** [comment]
cross-posting from https://github.com/github/docs/pull/11451#issuecomment-969552090
>@JLLeitschuh - the change you requested is now live on https://bounty.github.com/#legal_safe_harbor 🎉
>
thanks again for your ✨ contributions to these docs!
