### ISSUE TITLE
github.vscode-pull-request-github

### ISSUE THREAD

**Issue by huajin115** [github/site-policy#479]
**Please read our README.md and CONTRIBUTING.md files before creating an issue. If you are creating an issue to provide feedback about our Closed Policies, please note that we may not incorporate your feedback into our policies due to laws that limit our flexibility around those issues. If your feedback is not related to any of the questions below, feel free to delete the template questions and enter your comments in free form.**

**Comment by pcihon** [comment]
Hi @huajin115, I'm closing this as off topic because it appears you've added no content to the issue template. Please see our [Contributing.md](https://github.com/github/site-policy/blob/main/CONTRIBUTING.md) for the types of feedback we're looking for on our Site Policies in this repo.
