### ISSUE TITLE
Logical fallacy ToS clause addition

### ISSUE THREAD

**Issue by codegecko** [github/site-policy#48]
#### 1. What's the name of the policy?

Github ToS

#### 2. Is this issue related to a specific section within one of our policies (e.g. the Terms of Service)? If so, please include a link to the section or subsection.

N/A

#### 3. Did you already open a pull request? If so, please include a link to the PR.

No

#### 4. Sometimes it's easier to just put your feedback text into an issue. If that's how you'd prefer to contribute, this is the section to do that.

I would like to add a clause to the Github ToS that makes the use of logical fallacies in thread (discussions, issues, PRs, et al) a breach of the ToS, including (but not exclusively limited to) the list of logical fallacies found at https://en.wikipedia.org/wiki/List_of_fallacies.

#### 5. Why do you think this section or language needs improvement?

It is not uncommon for developers and contributors to deteriorate a discussion into using irrational arguments to justify their positions with regards to bugs, feature request, improvements, and suchforth.
Debates and positions taken on either side should be subject to their own merits, standalone, and use of a logical fallacy to attempt to invalidate an opposing party's position should subsequently invalidate the position of the party that used the fallacy.

Our job as programmers is to translate human requirements into logic trees that a computer can understand, to better facilitate the use of the software between humans. If we cannot agree to block out logical fallacies, then our software projects are more likely to fail, due to human reasons rather than technical merit.

**Comment by ssokolow** [comment]
The problem here is that, quite often, people who use logical fallacies don't even know the name for what they're doing and may even think that they're making a valid argument.

While this idea is well-intentioned, it has so much potential for unintended consequences and disproportionate response that, were it to be adopted, I'd start considering a move to BitBucket or GitLab.

**Comment by codegecko** [comment]
So, my view on this is in the mindset of "Rule #14": "do not fight with trolls, it means that they win".

By codifying banning the use of logical fallacies, it's easier to close a discussion, issue, or PR, due to breach of ToS, rather than have to spend time educating the opposing party as to why their argument is tautologically flawed. It's an easy way to avoid "Rule #14" issues on contentious topics.

**Comment by ssokolow** [comment]
The problem is that, by disallowing logical fallacies, you target the mechanism, regardless of intent.

Better to try to target the intent, regardless of mechanism, by making the against the ToS to do something such as "actively incite discord to non-constructive ends". (IANAL, so I'm sure someone more skilled could come up with a better phrasing.)

**Comment by codegecko** [comment]
I like this improvement. Hopefully Github has lawyers that can parse this intent :-)

**Comment by sstjohn** [comment]
Hell, let's make "submitting buggy pull requests" against the ToS. Or maybe "utterly misguided issue tickets."

**Comment by evandrocoan** [comment]
> @codegecko By codifying banning the use of logical fallacies, it's easier to close a discussion, issue, or PR, due to breach of ToS

You can employ a [Code of Conduct](https://en.wikipedia.org/wiki/Code_of_conduct) to your repositories, so you can close them by violation of your repository code of conduct. See the GitHub article:

1. [Adding a code of conduct to your project](https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/)

**Comment by nukeop** [comment]
let's make it a bannable offense to be uninformed about something

**Comment by bean5** [comment]
I think the general consensus here is that (1) owners of individual repositories or projects are already empowered and (2) banning trolling is more intuitive and less prone to banning people we'd like to keep than banning logical fallacies.

So we either closer this and mark as already done, or we can trolling. What is the consensus if those were the only options?

**Comment by codegecko** [comment]
Fair enough. Happy to close.
