### ISSUE TITLE
Email message uses wrong timezone

### ISSUE THREAD

**Issue by ziggythehamster** [github/site-policy#49]
The e-mail says to submit comments by 5PM PST on July 28. July 28 falls within Pacific Daylight Time (PDT), not Pacific Standard Time (PST).

If you want to use a daylight savings agnostic abbreviation, you should use PT.

Also, you really should additionally list the UTC offset, e.g. 5PM PDT (UTC-7).

**Comment by bluemazzoo** [comment]
@ziggythehamster Thank you for that contribution.

We'll keep that in mind in future blog posts and emails.
