### ISSUE TITLE
Bate

### ISSUE THREAD

**Issue by shanghan345** [github/site-policy#510]
**Please read our README.md and CONTRIBUTING.md files before creating an issue. If you are creating an issue to provide feedback about our Closed Policies, please note that we may not incorporate your feedback into our policies due to laws that limit our flexibility around those issues. If your feedback is not related to any of the questions below, feel free to delete the template questions and enter your comments in free form.**

#### 5. Why do you think this section or language needs improvement?
沒有一個是我喜歡的

**Comment by margaret-tucker** [comment]
I'm closing this as off topic. Please see our Contributing.md for the types of feedback we're looking for on our Site Policies in this repo.
