### ISSUE TITLE
#121 jose rios aisu   solo minusculas este es mi nombre

### ISSUE THREAD

**Issue by Milujem** [github/site-policy#517]
#121 jose rios aisu   solo minusculas este es mi nombre

_Originally posted by @Rojo872 in https://github.com/github/site-policy/issues/492#issuecomment-999298112_

**Comment by margaret-tucker** [comment]
I'm closing this as off topic. Please see our [Contributing.md](https://github.com/github/site-policy/blob/main/CONTRIBUTING.md) for the types of feedback we're looking for on our Site Policies in this repo.
