### ISSUE TITLE
Site doninin〽️

### ISSUE THREAD

**Issue by ManoelhenriqueKANdJWkxnnsaj** [github/site-policy#525]
Opa tropa,se não for escrito nem vem kkk 
 Eu sou novo nisso mais queria, ficar no YouTube por isso se escreve e comenta muito - pra mim ficar feliz.

**Comment by margaret-tucker** [comment]
I'm closing this as off topic. Please see our [Contributing.md](https://github.com/github/site-policy/blob/main/CONTRIBUTING.md) for the types of feedback we're looking for on our Site Policies in this repo.
