### ISSUE TITLE
Domínguez

### ISSUE THREAD

**Issue by Rica35** [github/site-policy#537]
[**![image](https://user-images.githubusercontent.com/51893303/155890221-fdc69379-9502-4634-acc6-e710946a7433.png)**]()

**Comment by Kapa2020** [comment]
Please email me rica35 or respond to this message if it’s you

**Comment by margaret-tucker** [comment]
I'm closing this as off topic. Please see our [Contributing.md](https://github.com/github/site-policy/blob/main/CONTRIBUTING.md) for the types of feedback we're looking for on our Site Policies in this repo.
