### ISSUE TITLE
Ricardo Domínguez

### ISSUE THREAD

**Issue by Rica35** [github/site-policy#540]

**Comment by margaret-tucker** [comment]
I'm closing this as off topic. Please see our [Contributing.md](https://github.com/github/site-policy/blob/main/CONTRIBUTING.md) for the types of feedback we're looking for on our Site Policies in this repo.

**Comment by Kapa2020** [comment]
Habla Porfavor kiké

**Comment by Kapa2020** [comment]
![BFBD5C2D-915C-44E5-9C7C-57212C5878CE](https://user-images.githubusercontent.com/100491340/156891422-ec5763d3-73b5-4a0a-8780-82b790e16d37.jpeg)
