### ISSUE TITLE
تطبيق 〖𝔸𝕒〗Fonts لأجهزة iPhone و Android ـ www.fontskeyboard.com/share

### ISSUE THREAD

**Issue by m-sk84** [github/site-policy#548]

**Comment by m-sk84** [comment]
>

**Comment by margaret-tucker** [comment]
I'm closing this as off topic. Please see our [Contributing.md](https://github.com/github/site-policy/blob/main/CONTRIBUTING.md) for the types of feedback we're looking for on our Site Policies in this repo.
