### ISSUE TITLE
Handle the situations of user death or disablement 

### ISSUE THREAD

**Issue by imhogan** [github/site-policy#55]
I believe that it would be useful to cater for the case of death or incapacity of a GitHub user in the [GitHub Terms of Service Cancellation and Termination section](https://help.github.com/articles/github-terms-of-service/#l-cancellation-and-termination) 
In essence it should be possible for an executor or carer operating under a valid power of attorney to notify GitHub of the death or incapacity of a user. This should result in the account profile being updated accordingly, preventing further activity by that account and ceasing email notifications, eg from watched repositories, etc. 
Watchers of the affected user's respositories should be notified of this event, and perhaps be able to post their condolences to the user's profile.
GitHub should probably reserve the right to remove any repositories after an appropriate period, which would allow interested users to fork any repository they wish to continue developing.
Having just updated my will - as a matter of course, not for any health reason - I have started looking at the issue of digital estates. 
This [Wikipedia page](https://en.m.wikipedia.org/wiki/Death_and_the_Internet) may also be of interest.
Hope this helps.
Blessings,
Ian Hogan.

**Comment by nsqe** [comment]
Thank you so much for bringing this up, @imhogan.

We do have a process for memorializing accounts of deceased users, and verifying their next of kin who want to administer digital assets. However, we have not yet made that process public or referred to it in our Terms of Service. I believe it would probably be better suited for our help documentation than our Terms of Service, but I do agree that we _should_ make that policy more public. I'm really glad that you brought this up so we can take action on it. Thank you.

I'm going to close this issue for now, but I'm opening an internal issue to get started drafting this documentation.
