### ISSUE TITLE
Scraping policy

### ISSUE THREAD

**Issue by KOLANICH** [github/site-policy#56]
#### 1. What's the name of the policy?
https://github.com/github/site-policy/blob/master/Policies/github-terms-of-service.md
#### 2. Is this issue related to a specific section within one of our policies (e.g. the Terms of Service)? If so, please include a link to the section or subsection.
https://github.com/github/site-policy/blob/master/Policies/github-terms-of-service.md#5-scraping

#### 5. Why do you think this section or language needs improvement?

>5. Scraping
>Scraping refers to extracting data from our Website via an automated process, such as a bot or ***webcrawler***. You may scrape the website for the following reasons:

>Researchers may scrape public, non-personal information from GitHub for research purposes, only if any publications resulting from that research are open access.

1 You will never know if you will have the results to publish.
2 Is publishing a preprint on arxiv.org considered as "open access" even though the peer-reviewed version of the work is behind a paywall?

>Archivists may scrape GitHub for public data for archival purposes.

I don't see that search engines are allowed to scrape. It looks like that search engines are not allowed to scrape.

I have already discussed that with the support, but it's time to discuss it publicly, my suggestions are:
1 Create a webpage and API using which anyone can download a rather actual subset of the data in interest in a machine-readable (not HTML, but in a form either of database dump or a custom binary format, if it suits better, please don't use just a bunch of archived JSON/XML, it would take additional effort to put it into a DB) and compressed format. This is needed to reduce load to both GH servers and people's internet connections.
2 to give permission to anyone to scrape public data for any purpose, but reserve the right to give incorrect results.

q: Why not to disallow scraping for spamming and other evil purposes?
a: Because they will just ignore the ToS.

q: But won't disallowing this in ToS allow GH to prosecute the ones doing that?
a: They may be under non-cooperative juristiction. They also may be fully automated (not targeted to GH specifically) and too dumb to understand the ToS. Also IMHO prosecution for scraping is unacceptable. I know that it's only my opinion and GH policymakers may think it is acceptable, but it's GH service, do what you need/want to do, I just have expressed my opinion on the subject.

q: But how can GH stop abusers?
a: It cannot. They can mimic a web browser pretty well and can use a distributed network of infected co puters to avoid detectikn..

q: How about rate-limiting?
a: Write it into robots.txt as a recommendation and enforce as a part of anti-DoS measures.

q: But what if GH is going to make money on selling this data? Won;t allowi g scraping harm the profits?
a: Just do what you need/want. The recommendations above  are made assumming that GH is not trying to make money selling the data.

**Comment by nsqe** [comment]
Thanks, @KOLANICH.

Web scraping is a tricky topic. We worked very hard to write a balanced policy that allows some scraping, but limits abuses and requires scrapers to enact certain privacy-protective policies.

We appreciate your suggestions, but at this time, the site-policy repository is only for discussions of _policies_. We are not able to approve changes to GitHub functionality, such as new APIs.

**Comment by harry-wood** [comment]
I came here googling for scraping policy information. This policy text about scraping _"Researchers may scrape..." "Archivists may scrape..."_ is that present in live github policy docs anywhere? I guess it used to be, but was since rearranged. I can only find a [GitHub Acceptable Use Policies - Spam and inauthentic activity](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies#4-spam-and-inauthentic-activity-on-github) section which seems relevant. "excessive automated bulk activity" is disallowed, but that's less specific, not mentioning "scraping" directly, and certainly _"You may scrape the website for the following reasons"_

Over on this [github-crawler-lib repo](https://www.npmjs.com/package/github-crawler-lib#githubs-tos) I see they've lifted out the same text about researchers and archivist, but is that text old?

**Comment by mlinksva** [comment]
@harry-wood yes, it's in this repo at https://github.com/github/site-policy/blob/f05aeb95464408a8d854250b2033302e11cf395f/Policies/github-acceptable-use-policies.md#7-information-usage-restrictions which is rendered two sections below the one you linked at https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies#7-information-usage-restrictions but yes the language was made more general in #309

**Comment by ralyodio** [comment]
is there a data dump for public research somewhere? preferably a .torrent file?
