### ISSUE TITLE
Do not require email in order to signup and use the service

### ISSUE THREAD

**Issue by KOLANICH** [github/site-policy#58]
#### 1. What's the name of the policy?
https://github.com/github/site-policy/blob/github-tos-update-july-2017/Policies/github-terms-of-service.md
#### 2. Is this issue related to a specific section within one of our policies (e.g. the Terms of Service)? If so, please include a link to the section or subsection.
https://github.com/github/site-policy/blob/github-tos-update-july-2017/Policies/github-terms-of-service.md#b-account-terms

#### 5. Why do you think this section or language needs improvement?
First of all I wanna say that I had some discussion with the support on the topic.

E-mail system is too centralised nowadays. There are several free email services available to everyone usually on the terms which are far from acceptable for some people like me, for example many web services require it users to provide the service with a cellphone number and to prove the ownership of the account related to this number. Sometimes these web services can be required by the law to collect some information like cellphone numbers. Sometimes this services allow itself too much, for example scanning peoples emails for patterns.

So I think it's time to move further.
1 I think it's OK not to make people to provide email address. As I understand, the main purpose of providing email address is users' convenience (here I assume that GH doesn't send spam and doesn't sell the info collected), s.a. email notifications and replies with email and for access restore procedure (which can be done another way). So I have no idea why this has been made mandatory. So I propose to make this optional.

2 There is some software allowing decentralised messaging, most notably [BitMessage](https://github.com/Bitmessage/PyBitmessage) and Tox, all of which have own pros and cons. The pros is confidentiality of the content and independence from malicious companies. The cons are high resource usage due to decentralised nature, leaking some metadata to all the world, not only to restricted set of powerful parties and some functionality limitations, such as limited lifetime of offline messages (28 days for BitMessage or no such at all for Tox). Some people would consider some the drawbacks as tolerable cost for better privacy and security.
So I propose to support these messagging systems too, even though they are experimental.

**Comment by nsqe** [comment]
Thanks, @KOLANICH.

These are really interesting ideas, but again, the site-policy repository is only for discussion of GitHub _policies_. We aren't able to build in this kind of functionality into GitHub.
