### ISSUE TITLE
Welcome, and early access

### ISSUE THREAD

**Issue by nsqe** [github/site-policy#6]
Welcome to the Site Policy repository!

### Early access

If you're reading this in the week before June 21, you're one of our Site Policy testers. Thanks for sending us feedback on our Terms of Service back in February — we really appreciate it. Please poke around, take a look at our [open pull requests](https://github.com/github/site-policy/pulls), and let us know what you think. We've tried to take our users' feedback to heart, both in creating this repository and in updating our Terms.

We look forward to your feedback on the Site Policy process. We might make a few tweaks to that before the public launch on June 21, based on your feedback. However, we won't make any changes to the Terms of Service update until the rest of our community has had a chance to weigh in. We want that dialogue to be open.

### Open access

If you're reading this as part of our June 21 launch, welcome! As above, please take a look at our [open pull requests](https://github.com/github/site-policy/pulls). We really look forward to your feedback, both on the pull requests we currently have open and on any suggestions you have to our other policies.

**Comment by bluemazzoo** [comment]
This repository is now public!
