### ISSUE TITLE
TOS Typo

### ISSUE THREAD

**Issue by MarcM001** [github/site-policy#60]
Corporate TOS issue: “If you're posting anything you or your Users did not create yourselves and on your behalf, **you agrees** that…” Fix typo.

**Comment by nsqe** [comment]
Yikes! Thanks, @MarcM001. We'll take a look!

**Comment by bluemazzoo** [comment]
@MarcM001 Thanks for your contribution! That typo has been fixed in the [draft update](https://github.com/github/site-policy/blob/github-corporate-tos-update-july-2017/Policies/github-corporate-terms-of-service.md#3-ownership-of-content-right-to-post-and-license-grants).

**Comment by wking** [comment]
On Fri, Jul 28, 2017 at 02:01:41PM -0700, Joe Mazzella wrote:
> That typo has been fixed in the draft update.

Cross-linking #2, which is the PR for that
github-corporate-tos-update-july-2017 branch.
