### ISSUE TITLE
Access to data in connection with service interruptions/termination

### ISSUE THREAD

**Issue by MarcM001** [github/site-policy#62]
Corporate TOS issue: Section L3, you can suspend access at any time without notice or cause and seemingly no obligation to help users extract  data. Section L3, you can terminate on 30 days’ notice, with an obligation to support extracting data. 

Unclear why indefinite suspension should potentially lead to a worse result than termination.  Consider clarifying that you’ll provide data extract access for suspensions lasting longer than 30 days. 

Related in Section Q, “We reserve the right at any time and from time to time to modify or discontinue, temporarily or permanently, the Website (or any part of it) with or without notice.” Are you able to provide any assurances about data extraction in this context?

**Comment by nsqe** [comment]
Thanks, @MarcM001.

You're right, this was pretty confusing. We're rewriting it and making it much clearer. We should have the new version posted shortly. Thank you for bringing our attention to it!
