### ISSUE TITLE
الاسم:                    IEToEdge BHO الناشر:                   Microsoft Corporation النوع:                    كائن مساعد المستعرض البنية:                   32 بت و64 بت الإصدار:                  105.0.1343.27 تاريخ الملف:              ‏02 ‏سبتمبر, ‏2022, ‎‏07:58 م تاريخ آخر وصول:           غير متوفر معرف الفئة:               {1FD49718-1D00-4B19-AF5F-070AF6D5D54C} عدد مرات الاستخدام:       0 عدد العناصر الممنوعة:     0 الملف:                    ie_to_edge_bho_64.dll المجلد:                   C:\Program Files (x86)\Microsoft\Edge\Application\105.0.1343.27\BHO

### ISSUE THREAD

**Issue by Hebamabrouk** [github/site-policy#621]
**Please read our README.md and CONTRIBUTING.md files before creating an issue. If you are creating an issue to provide feedback about our Closed Policies, please note that we may not incorporate your feedback into our policies due to laws that limit our flexibility around those issues. If your feedback is not related to any of the questions below, feel free to delete the template questions and enter your comments in free form.**

**Comment by margaret-tucker** [comment]
I'm closing this as off topic. Please see our [Contributing.md](https://github.com/github/site-policy/blob/main/CONTRIBUTING.md) for the types of feedback we're looking for on our Site Policies in this repo.
