### ISSUE TITLE
TOS enforceability comment 

### ISSUE THREAD

**Issue by MarcM001** [github/site-policy#63]
Corporate TOS issue: Section R4, “If any part of this Agreement is held invalid or unenforceable, that portion of the Agreement will be construed to reflect the parties’ original intent.” Consider if this works as a blue pencil clause—if the intent unenforceable, no other expression of that intent would be enforceable, so a court might reject wholesale the applicable part of the agreement. Consider if you would be better protected by saying “[the parties] [a court] will reform that portion of the agreement to reflect the parties’ original intent as nearly as possible.”

**Comment by nsqe** [comment]
Hey, @MarcM001,

We took a closer look at this, and I think the wording in the Terms of Service says pretty much the same thing as your suggested wording. Additionally, it's very standard phrasing in contract law. Thanks for the suggestion!
