### ISSUE TITLE
Request for mutuality

### ISSUE THREAD

**Issue by MarcM001** [github/site-policy#64]
Corporate TOS issue: Section R4,  “Any failure on the part of GitHub to enforce any provision of this Agreement will not be considered a waiver of our right to enforce such provision. Our rights under this Agreement will survive any termination of this Agreement.” 

Please consider making both of these clauses mutual out of fairness.

**Comment by nsqe** [comment]
Thanks for the suggestion, @MarcM001.

Unfortunately, we're not able to do that right now. Instead, we have tried to create an agreement that is, by default, as balanced and user-favorable as possible.
