### ISSUE TITLE
Duplicate of #

### ISSUE THREAD

**Issue by Turki999999** [github/site-policy#642]
Duplicate of #

_Originally posted by @Turki999999 in https://github.com/github/site-policy/pull/582#pullrequestreview-1118998268_
      

https://github.com/github/site-policy/issues/642#tasklist-block-92bd3dc5-7fb3-49bd-9b50-e5c62dcab45c

**Comment by margaret-tucker** [comment]
I'm closing this as off topic. Please see our [Contributing.md](https://github.com/github/site-policy/blob/main/CONTRIBUTING.md) for the types of feedback we're looking for on our Site Policies in this repo.
