### ISSUE TITLE
LICENSE DAI

### ISSUE THREAD

**Issue by DAIDAOXING** [github/site-policy#653]
**Please read our README.md and CONTRIBUTING.md files before creating an issue. If you are creating an issue to provide feedback about our Closed Policies, please note that we may not incorporate your feedback into our policies due to laws that limit our flexibility around those issues. If your feedback is not related to any of the questions below, feel free to delete the template questions and enter your comments in free form.**

**Comment by Buyboy** [comment]
> **Please read our README.md and CONTRIBUTING.md files before creating an issue. If you are creating an issue to provide feedback about our Closed Policies, please note that we may not incorporate your feedback into our policies due to laws that limit our flexibility around those issues. If your feedback is not related to any of the questions below, feel free to delete the template questions and enter your comments in free form.**
> 
> #### 1. What's the name of the policy?
> #### 2. Is this issue related to a specific section within one of our policies (e.g. the Terms of Service)? If so, please include a link to the section or subsection.
> #### 3. Did you already open a pull request? If so, please include a link to the PR in the [GitHub Docs repo](https://github.com/github/docs).
> #### 4. Sometimes it's easier to just put your feedback text into an issue. If that's how you'd prefer to contribute, this is the section to do that.
> #### 5. Why do you think this section or language needs improvement?

**Comment by margaret-tucker** [comment]
I'm closing this as off topic. Please see our [Contributing.md](https://github.com/github/site-policy/blob/main/CONTRIBUTING.md) for the types of feedback we're looking for on our Site Policies in this repo.

**Comment by DAIDAOXING** [comment]
> Wind correlations are planned in special conditions
> To keep privacy and measures for large projects
> 
> 

TODO DIRECTO A CUENTA REAL DE DAI ACTIVACION UNICO SOLO DAOXING. TARJETA MASTE CARD ♦️♦️♦️
5320 1743 0211 9495 
O
TARJETA MASTER CARD
4188 2021 1688 8882
UNICO CORREOS ELECTRONICOS DE PRESIDENT CEO TAN BIEN DIRECTOR DE PAYMENT PARA GESTIONAR TODO REDES SOCIALES : DAOXINGDAIUNICO@GMAIL.COM
NOMBRE:DAI DAOXING
EMPRESA PRINCIPAL:DAI GLOBAL SA
EMPRESA EN REDES SOCIALES:DAI GLOBAL BUSINESS SA
EMPRESA PARA GESTIONAR UNICO :DAI GLOBAL BANK DIGITAL 
NIE:5800505C
PASAPORTE DE CHINA :E44167604
UNICO PERSONAL EN TODAS LAS EMPRESAS DE REDES SOCIALES PARA GESTIONAR TODO LOS TRABSJOS
