### ISSUE TITLE
Section G "API Terms", subsection 3 "GitHub May Terminate Your Use of the API".

### ISSUE THREAD

**Issue by chriswarrenstreet** [github/site-policy#66]
**Please read our README.md and CONTRIBUTING.md files before creating an issue. If you are creating an issue to provide feedback about our Closed Policies, please note that we may not incorporate your feedback into our policies due to laws that limit our flexibility around those issues. If your feedback is not related to any of the questions below, feel free to delete the template questions and enter your comments in free form.**

#### 1. What's the name of the policy?

Section G "API Terms", subsection 3 "GitHub May Terminate Your Use of the API".

#### 2. Is this issue related to a specific section within one of our policies (e.g. the Terms of Service)? If so, please include a link to the section or subsection.

Section G "API Terms", subsection 3 "GitHub May Terminate Your Use of the API".

#### 3. Did you already open a pull request? If so, please include a link to the PR.

N/A

#### 5. Why do you think this section or language needs improvement?

Would it be possible to have revocation of access to APIs occur only upon violation of the Terms of Service or other malicious activity rather than without cause? Further, would it be possible to have fifteen days' notice be provided for revocation of access?

**Comment by nsqe** [comment]
Thanks, @chriswarrenstreet. 

We need the ability to terminate API access immediately, because occasionally we come across someone abusing our API, such as by pulling down user data and reselling it as a service, or spamming our users.
