### ISSUE TITLE
Section L "Cancellation and Termination" subsection 3 "GitHub May Terminate"

### ISSUE THREAD

**Issue by chriswarrenstreet** [github/site-policy#67]
**Please read our README.md and CONTRIBUTING.md files before creating an issue. If you are creating an issue to provide feedback about our Closed Policies, please note that we may not incorporate your feedback into our policies due to laws that limit our flexibility around those issues. If your feedback is not related to any of the questions below, feel free to delete the template questions and enter your comments in free form.**

#### 1. What's the name of the policy?

Terms of Service Section L "Cancellation and Termination" subsection 3 "GitHub May Terminate"

#### 2. Is this issue related to a specific section within one of our policies (e.g. the Terms of Service)? If so, please include a link to the section or subsection.

Terms of Service Section L "Cancellation and Termination" subsection 3 "GitHub May Terminate"

#### 3. Did you already open a pull request? If so, please include a link to the PR.

N/A

#### 5. Why do you think this section or language needs improvement?

Would it be possible to have termination only occur for cause with thirty days' notice versus for any reason without notice?

**Comment by nsqe** [comment]
Again, thanks, @chriswarrenstreet. 

We have _lots_ of people ask about this, and I'm very sympathetic: no one wants to fear losing their stuff. 

However, we need the ability to suspend or terminate accounts without notice. We are required by law to terminate repeat copyright infringers, and we can't give them thirty days' notice. We also have to close any accounts of children under 13 — again, without notice. Additionally, we need to be able to drop the 🔨  on spammers and other toxic users promptly, so they don't disrupt our community. 

And then there are the people who we need to suspend, even if they are not obviously in violation of our Terms of Service. For example, if an account gets compromised and used as a delivery source for malware, we need to be able to shut it off immediately, even if the user who owns the account isn't the one who posted the malware. 

We try to protect our users in other ways. For instance, if a user has been suspended, the user can always request a copy of their lawful, non-infringing account contents. We'll zip those up and send them right over, and we're going to make that language a little more clear.
