### ISSUE TITLE
Can we provide a more descriptive error message? 🤔

### ISSUE THREAD

**Issue by Rush2112hale** [github/site-policy#672]
Can we provide a more descriptive error message? 🤔 

__Originally posted by @Bibo-Joshi in https://github.com/python-telegram-bot/python-telegram-bot/pull/3322#discussion_r1010658146__

**Comment by margaret-tucker** [comment]
I'm closing this as off topic. Please see our Contributing.md for the types of feedback we're looking for on our Site Policies in this repo.
