### ISSUE TITLE
Publicity

### ISSUE THREAD

**Issue by AEITS** [github/site-policy#68]
**Please read our README.md and CONTRIBUTING.md files before creating an issue. If you are creating an issue to provide feedback about our Closed Policies, please note that we may not incorporate your feedback into our policies due to laws that limit our flexibility around those issues. If your feedback is not related to any of the questions below, feel free to delete the template questions and enter your comments in free form.**

#### 1. What's the name of the policy?

Corporate TOS draft

#### 2. Is this issue related to a specific section within one of our policies (e.g. the Terms of Service)? If so, please include a link to the section or subsection.

https://github.com/github/site-policy/compare/github-corporate-tos-update-july-2017
Line 367

#### 3. Did you already open a pull request? If so, please include a link to the PR.

N/A

#### 5. Why do you think this section or language needs improvement?

In section 6 on Publicity.  It's not clear that the right to use the company name for promotion continues or does not continue after the company name is no longer publicly displayed.

**Comment by bluemazzoo** [comment]
@AEITS Thanks for the contribution! We will update that section to provide more clarity.
