### ISSUE TITLE
New

### ISSUE THREAD

**Issue by skyboi1233** [github/site-policy#686]
__Originally posted by @skyboi1233 in https://github.com/skyboi1233/Skyler/issues/2__

**Comment by skyboi1233** [comment]
> __Originally posted by @skyboi1233 in https://github.com/skyboi1233/Skyler/issues/2__

**Comment by margaret-tucker** [comment]
I'm closing this as off topic. Please see our [Contributing.md](https://github.com/github/site-policy/blob/main/CONTRIBUTING.md) for the types of feedback we're looking for on our Site Policies in this repo.
