### ISSUE TITLE
> The official response could have came out earlier ..

### ISSUE THREAD

**Issue by rifanahmedluman** [github/site-policy#688]
> The official response could have came out earlier ..

Define official

_Originally posted by @Karmavil in https://github.com/github/site-policy/issues/582#issuecomment-1235538051_

**Comment by margaret-tucker** [comment]
I'm closing this as off topic. Please see our [Contributing.md](https://github.com/github/site-policy/blob/main/CONTRIBUTING.md) for the types of feedback we're looking for on our Site Policies in this repo.
