### ISSUE TITLE
Not sure why there is no "Report" option in this repo but this seems like spam.

### ISSUE THREAD

**Issue by rifanahmedluman** [github/site-policy#689]
Not sure why there is no "Report" option in this repo but this seems like spam.

_Originally posted by @Consolatis in https://github.com/github/site-policy/issues/687#issuecomment-1374891702_

**Comment by margaret-tucker** [comment]
I'm closing this as off topic. Please see our [Contributing.md](https://github.com/github/site-policy/blob/main/CONTRIBUTING.md) for the types of feedback we're looking for on our Site Policies in this repo.
