### ISSUE TITLE
For clarity and technical correctness, replace "pixel tag" with "tracking pixel"

### ISSUE THREAD

**Issue by ossguy** [github/site-policy#70]
#### 1. What's the name of the policy?

https://github.com/github/site-policy/blob/master/Policies/github-privacy-statement.md

#### 2. Is this issue related to a specific section within one of our policies (e.g. the Terms of Service)? If so, please include a link to the section or subsection.

https://github.com/github/site-policy/blob/master/Policies/github-privacy-statement.md#how-we-communicate-with-you

#### 5. Why do you think this section or language needs improvement?

The term "pixel tag" does not convey what the pixel does.  The term also does not properly describe to a technical person what it is.  Normally when one says "X tag", they mean "&lt;X&gt;", but there is no &lt;pixel&gt; in standard HTML so "pixel tag" is confusing.

Thus the privacy statement should use "tracking pixel" instead of "pixel tag" in the four places it is mentioned (3 in the section linked above and 1 in https://github.com/github/site-policy/blob/master/Policies/github-privacy-statement.md#tracking ).

With the above change, the "pixel tag" paragraph at least makes a bit more sense.  I'm still not a fan of its middle sentence ("We use this pixel tag [/tracking pixel] to make our email more effective for you and to make sure we’re not sending you unwanted email") since I don't understand how that makes email more effective or determines whether I want the email (as my email client never loads such pixels so I don't know how GitHub could determine whether I want an email based on tracking pixels).  But at least with my suggested change the reader knows that the pixel is used for tracking purposes (and so I don't think fixing that sentence would be as critical after my change).

**Comment by wking** [comment]
On Fri, Jul 28, 2017 at 05:39:40PM +0000, Denver Gingerich wrote:
> The term "pixel tag" does not convey what the pixel does… Thus the
> privacy statement should use "tracking pixel" instead of "pixel
> tag"…

According to Wikipedia, both “tracking pixel” and “pixel tag” are
common names for the same thing [1].  Personally, I agree that
“tracking pixel” is a more descriptive name, so I'm in favor of the
switch your suggesting unless someone can show that “pixel tag” is
significantly more popular.

[1]: https://en.wikipedia.org/wiki/Web_beacon

**Comment by nsqe** [comment]
In all the work I've done in this field, they're used interchangeably. I don't believe this is confusing; people know what pixel tags, web beacons, and tracking pixels are.
