### ISSUE TITLE
Bigo.live

### ISSUE THREAD

**Issue by mohammadfarari1360** [github/site-policy#710]
Your friend محمد فراری شاه ب invite you to join ludo talent: https://bigo.onelink.me/1168916328/p4po3fss

**Comment by Starr55** [comment]
> Your friend محمد فراری شاه ب invite you to join ludo talent: https://bigo.onelink.me/1168916328/p4po3fss

Enjoy

**Comment by margaret-tucker** [comment]
I'm closing this as off topic. Please see our [Contributing.md](https://github.com/github/site-policy/blob/main/CONTRIBUTING.md) for the types of feedback we're looking for on our Site Policies in this repo.
