### ISSUE TITLE
Make it clear that GitHub uses its public policies to adjudicate UGC removal

### ISSUE THREAD

**Issue by ossguy** [github/site-policy#73]
#### 1. What's the name of the policy?

https://github.com/github/site-policy/blob/master/Policies/github-terms-of-service.md

#### 2. Is this issue related to a specific section within one of our policies (e.g. the Terms of Service)? If so, please include a link to the section or subsection.

https://github.com/github/site-policy/blob/master/Policies/github-terms-of-service.md#3-github-may-remove-content

#### 5. Why do you think this section or language needs improvement?

This section states that GitHub may remove any User-Generated Content (UGC) that "violates any GitHub terms or policies" without stating or defining which terms or policies those might be.  As a result, UGC could be removed for arbitrary reasons (to the user), since GitHub may claim the UGC violates some internal GitHub policy that the user doesn't know about.

As a result, "violates any GitHub terms or policies" should be changed to "violates the Agreement", since Agreement is an already-defined term that covers GitHub's publicly-available policies.

**Comment by wking** [comment]
On Fri, Jul 28, 2017 at 06:07:59PM +0000, Denver Gingerich wrote:
> As a result, "violates any GitHub terms or policies" should be
> changed to "violates the Agreement", since Agreement is an
> already-defined term that covers GitHub's publicly-available
> policies.

I like this change, although the “in our sole discretion” clause makes
the removal basically “because GitHub wants to” regardless of which
document(s) nominally anchor the decision.

[1]: https://github.com/github/site-policy/blob/75c016d80fe819c192f5c953eb3829bee63462a2/Policies/github-terms-of-service.md#3-github-may-remove-content

**Comment by pooomhfhfgsdfddf** [comment]
> #### 1. นโยบายมีชื่อว่าอะไร
> ขอโทษสมาชิกทุกคนด้วยทางเรายังไม่พร้อมไห่่ใช้งานhttps://github.com/github/site-policy/blob/master/Policies/github-terms-of-service.md
> 
> #### 2. ปัญหานี้เกี่ยวข้องกับหัวข้อเฉพาะภายในนโยบายของเรา (เช่นข้อกำหนดในการให้บริการ) หรือไม่ ถ้าเป็นเช่นนั้นโปรดรวมลิงค์ไปยังส่วนหรือส่วนย่อย
> https://github.com/github/site-policy/blob/master/Policies/github-terms-of-service.md#3-github-may-remove-content
> 
> #### 5. ทำไมคุณคิดว่าส่วนหรือภาษานี้ต้องมีการปรับปรุง
> ส่วนนี้ระบุว่า GitHub อาจลบเนื้อหาใด ๆ ที่ผู้ใช้สร้างขึ้น (UGC) ที่ "ละเมิดข้อกำหนดหรือนโยบาย GitHub ใด ๆ " โดยไม่ระบุหรือกำหนดข้อกำหนดหรือนโยบายใดที่อาจเป็น เป็นผลให้ UGC สามารถลบออกได้ด้วยเหตุผลตามอำเภอใจ (สำหรับผู้ใช้) เนื่องจาก GitHub อาจอ้างว่า UGC ละเมิดนโยบาย GitHub ภายในบางอย่างที่ผู้ใช้ไม่ทราบ
> 
> As a result, "violates any GitHub terms or policies" should be changed to "violates the Agreement", since Agreement is an already-defined term that covers GitHub's publicly-available policies.

**Comment by pooomhfhfgsdfddf** [comment]
> #### 1. นโยบายมีชื่อว่าอะไร
> https://github.com/github/site-policy/blob/master/Policies/github-terms-of-service.md
> 
> #### 2. ปัญหานี้เกี่ยวข้องกับหัวข้อเฉพาะภายในนโยบายของเรา (เช่นข้อกำหนดในการให้บริการ) หรือไม่ ถ้าเป็นเช่นนั้นโปรดรวมลิงค์ไปยังส่วนหรือส่วนย่อย
> https://github.com/github/site-policy/blob/master/Policies/github-terms-of-service.md#3-github-may-remove-content
> 
> #### 5. ทำไมคุณคิดว่าส่วนหรือภาษานี้ต้องมีการปรับปรุง
> ส่วนนี้ระบุว่า GitHub อาจลบเนื้อหาใด ๆ ที่ผู้ใช้สร้างขึ้น (UGC) ที่ "ละเมิดข้อกำหนดหรือนโยบาย GitHub ใด ๆ " โดยไม่ระบุหรือกำหนดข้อกำหนดหรือนโยบายใดที่อาจเป็น เป็นผลให้ UGC สามารถลบออกได้ด้วยเหตุผลตามอำเภอใจ (สำหรับผู้ใช้) เนื่องจาก GitHub อาจอ้างว่า UGC ละเมิดนโยบาย GitHub ภายในบางอย่างที่ผู้ใช้ไม่ทราบ
> 
> ดังนั้นควร "เปลี่ยนข้อกำหนดหรือนโยบายใด ๆ ของ GitHub" เป็น "ละเมิดข้อตกลง" เนื่องจากข้อตกลงเป็นคำที่กำหนดไว้แล้วซึ่งครอบคลุมนโยบายที่เปิดเผยต่อสาธารณะของ GitHub

ขอโทษจิงๆเรากํารังเพิมพลิตพัตอยู่โปรดรอสักครุ

**Comment by Aspie96** [comment]
This is an old issue, but I believe it to be a great idea.
Is there any progress on this?

**Comment by UschiSushi** [comment]
Uiiii

**Comment by abent999** [comment]
Decline

**Comment by UschiSushi** [comment]
Ablehnen

[Uschi Czecha - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=lvevf)	[lvevf]

On July 22, 2020 at 18:14 GMT, abent999 <notifications@github.com> wrote:

Decline

**Comment by vollmera** [comment]
Regarding Section D2 of our Terms of Service, specifically:

>refuse or remove any User-Generated Content that, in our sole discretion, violates any GitHub terms or policies.

I opened #274 to add a link to the site policy section of GitHub Help to make it more explicit what is meant by any GitHub terms or policies.

Thanks very much for the feedback!
