### ISSUE TITLE
@yufang67, Thank you for the confirmation and this issue we'll consider as feature requestLe problème signalé est basé sur un seul GPU A100 80G. 

### ISSUE THREAD

**Issue by Luckylotus17** [github/site-policy#744]
@yufang67, Merci pour la confirmation et ce problème que nous considérerons comme une demande de fonctionnalité 

Bonjour @sachinprasadhs 

Pourriez-vous s’il vous plaît examiner cette question ? Merci!

_Originally posté par @gaikwadrahul8 dans https://github.com/tensorflow/tensorflow/issues/59728#issuecomment-1454729744_tensorflow/tensorflow/issues/59728#issuecomment- [ ] -1454729744_[]()

**Comment by margaret-tucker** [comment]
I'm closing this as off topic. Please see our [Contributing.md](https://github.com/github/site-policy/blob/main/CONTRIBUTING.md) for the types of feedback we're looking for on our Site Policies in this repo.
