### ISSUE TITLE
Ayuda 

### ISSUE THREAD

**Issue by fcblack24** [github/site-policy#747]
¡No todas las apps son seguras! ¡Al igual que yo, verifica siempre la seguridad de tus apps! #behappywithKISA

https://kas.pr/Mobile![EBD876AF1D5F865EA4F969631EEB28D2.png](https://user-images.githubusercontent.com/128683223/230536789-d07187e7-624e-45ef-b597-6c302be5b25f.png)  fcblack245@gmail.com

**Comment by margaret-tucker** [comment]
I'm closing this as off topic. Please see our [Contributing.md](https://github.com/github/site-policy/blob/main/CONTRIBUTING.md) for the types of feedback we're looking for on our Site Policies in this repo.
