### ISSUE TITLE
tokenacceso

### ISSUE THREAD

**Issue by Pedro923** [github/site-policy#749]
https://github.com/pmahsky/FloatingActionMenuAndroid/commit/d4b922a434958120d1d76e12bffcc5a96debfe04

**Comment by margaret-tucker** [comment]
I'm closing this as off topic. Please see our [Contributing.md](https://github.com/github/site-policy/blob/main/CONTRIBUTING.md) for the types of feedback we're looking for on our Site Policies in this repo.
