### ISSUE TITLE
Enshrine existing always-email-updates policy into Terms of Service

### ISSUE THREAD

**Issue by ossguy** [github/site-policy#75]
#### 1. What's the name of the policy?

https://github.com/github/site-policy/blob/master/Policies/github-terms-of-service.md

#### 2. Is this issue related to a specific section within one of our policies (e.g. the Terms of Service)? If so, please include a link to the section or subsection.

https://github.com/github/site-policy/blob/master/Policies/github-terms-of-service.md#q-changes-to-these-terms

#### 5. Why do you think this section or language needs improvement?

As in the Privacy Statement, this section requires that users check the Website at least as often as every 30 days, otherwise they might not be aware of new terms that apply to them.

Similar to #71, I suggest that this section mention that GitHub will also (and always) additionally inform the user by email, at least for any "material changes".  This seems to be the norm at GitHub already, so it should make no difference to GitHub to make it explicit, and means that users don't have to keep re-reading the entire Agreement every few weeks to ensure they haven't missed something.  Currently this section says only that users will be notified "by posting a notice on our Website", even though the Agreement applies to the Service, which consists of far more than just the Website.

**Comment by nsqe** [comment]
Responded in https://github.com/github/site-policy/issues/71.
