### ISSUE TITLE
Add Icons to the Terms of Service

### ISSUE THREAD

**Issue by eknox6** [github/site-policy#76]
#### 1. What's the name of the policy?
https://github.com/github/site-policy/blob/master/Policies/github-terms-of-service.md

#### 2. Is this issue related to a specific section within one of our policies (e.g. the Terms of Service)? If so, please include a link to the section or subsection.
Entire document.

#### 5. Why do you think this section or language needs improvement?
Many other websites are adding icons to their legal documents to make them easier to understand. One particular organization that does a great job of this is [Creative Commons](https://creativecommons.org/share-your-work/licensing-types-examples/). Using icons would help users that skim the document be able to gain an understanding from a glance at these symbols, so even if they did not read the text, they would still get the gist of the terms. This would be mutually beneficial for GitHub and for users because of the increased likelihood of users understanding the document's contents.

**Comment by nsqe** [comment]
There's been a lot of work in this field — Mozilla did some great work proposing [icons for privacy policies](https://wiki.mozilla.org/Privacy_Icons) several years ago, for instance. 

However, they've never been standardized, especially for Terms of Service. Even Creative Commons, which you reference, only uses icons for their _licenses_, but not for their actual _[Terms of Service agreement](https://creativecommons.org/terms/)_. Disconnect has tried to adopt them for [use in privacy](https://disconnect.me/icons), but still has to do a lot of explaining to establish what the icons actually mean.

I would love for us to get to a point at which we have some universally standard, easily-recognizable icons for privacy and terms of service. Right now, we don't. In the absence of icons, we'll stick to working on making the text of our Terms of Service as easy to understand as possible.
