### ISSUE TITLE
Present the Terms of Service in a scrollable window for users when creating an account

### ISSUE THREAD

**Issue by eknox6** [github/site-policy#77]
#### 1. What's the name of the policy?
https://github.com/github/site-policy/blob/master/Policies/github-terms-of-service.md

#### 2. Is this issue related to a specific section within one of our policies (e.g. the Terms of Service)? If so, please include a link to the section or subsection.
Related to the account creation process, not the contents of the document.

#### 5. Why do you think this section or language needs improvement?
Currently, during the account creation process users do not actually have to acknowledge that there is a Terms of Service and they agree by clicking a button or checkbox (there is just text that says by clicking sign up you agree). It would be beneficial for legal purposes for GitHub to make this change and make users confirm their agreement, but it would also give a better opportunity for users to look at the Terms of Service. Rather than having to find the page, it would be put in front of them automatically, increasing their likelihood of reading the terms.

**Comment by nsqe** [comment]
Thanks for the suggestion, @eknox6.

We'll give that some thought. However, the site-policy repository is intended for discussions about the content of the policies, not for proposals about additional functionality for GitHub. At this time, we don't have the ability to create new pop-up windows for the Terms of Service on GitHub.
