### ISSUE TITLE
Add "Print" and "Download" buttons to the Terms of Service document

### ISSUE THREAD

**Issue by eknox6** [github/site-policy#78]
#### 1. What's the name of the policy?
https://github.com/github/site-policy/blob/master/Policies/github-terms-of-service.md

#### 2. Is this issue related to a specific section within one of our policies (e.g. the Terms of Service)? If so, please include a link to the section or subsection.
Top of document (before table of contents)

#### 5. Why do you think this section or language needs improvement?
It would be helpful for users to have simple buttons to click to allow them to print or download the document in a format prepared for printing (rather than having to print or download the page using the standard browser features).

**Comment by nsqe** [comment]
Thanks, we'll take a look. While most people who use GitHub are familiar enough with their browser's functionality to print a web page, it might be more convenient for them to have a simple download button.
