### ISSUE TITLE
Hello world 

### ISSUE THREAD

**Issue by ziggy74ai** [github/site-policy#781]
http
s://docs.github.com/en/get-started/quickstart/hello-world#:~:text=pull%20requests.%20You%27ll-,create,-your%20own%20Hello![chrome_stylized_highlight_2300805584823559700.png](https://github.com/github/site-policy/assets/131272874/0fb99c1b-a378-45e4-bb12-3b55b24e01ca)

**Comment by margaret-tucker** [comment]
I'm closing this as off topic. Please see our [Contributing.md](https://github.com/github/site-policy/blob/main/CONTRIBUTING.md) for the types of feedback we're looking for on our Site Policies in this repo.
