### ISSUE TITLE
Outdated  how to update all

### ISSUE THREAD

**Issue by Galbert01** [github/site-policy#794]
You lost me at `ads for enterprise users`.

_Originally posted by @jdgregson in https://github.com/github/site-policy/issues/582#issuecomment-1203330510_

**Comment by margaret-tucker** [comment]
I'm closing this as off topic. Please see our [Contributing.md](https://github.com/github/site-policy/blob/main/CONTRIBUTING.md) for the types of feedback we're looking for on our Site Policies in this repo.
