### ISSUE TITLE
OSS licences vs. ToS: moral rights

### ISSUE THREAD

**Issue by mirabilos** [github/site-policy#8]
Even after https://github.com/github/site-policy/pull/1 there are still some remaining issues. This one is about §D.7 (moral rights).

I fear I must state that the presence of this section *still* **excludes all OSS licences requiring attribution** if the work comes from a nōn-GitHub source who is also someone other than the person uploading it to GitHub.

Licences such as CC-BY, but also (at least 4-clause) BSD and (with a *much* wider impact) Apache 2 licence with a NOTICE file, require retaining attribution.

As I stated in February, I believe this is the “cheap way out” of something that can be solved with some very minor technical effort. Please let me elaborate:

You stated (in the pre-pull#1 ToS) that this is necessary for search functionality. Such functionality can either be done by others (crawling GitHub and presenting the results), in which case you’re not responsible as long as the changes from https://github.com/github/site-policy/issues/7 are applied and those others are required to fulfil those licences themselves, or by GitHub.

I believe that it is customary to display search results with a link to the original in its context. I believe it would be enough to fulfil those licences’ attribution requirements if you put a notice on each search result page/snippet stating that these are excerpts for search, which are not in the Public Domain but are covered by copyright and neighbouring laws, and the terms under which those are available can be found if one follows the link to the original in its context.

In the USA, you may even get by with citing “fair use”.

----

One thing I noticed in the post-pull#1 wording is that it only applies to “Your Content”, which is defined as content that the person uploading it to GitHub creates or owns. Is this deliberate?

If yes, and this is made explicit (either by commenting here or by adjusting the wording), I believe this clause can stay as-is *but will not help you* as people can still upload content created by others under licences requiring attribution without those others needing to waive that assertion right. (Unfairness to those who do publish to GitHub aside, then.)

So, in the end, I believe it’s better if §D.7 is removed in its entirety and small technical measures to ensure it’s not necessary are invented.

I could also live with §D.7 being amended to make it trigger only for work not under one of the OSS licences I pointed out in https://github.com/github/site-policy/issues/7

----

This is a follow-up on a part of the new ToS draft, partly from [my prior review](http://www.mirbsd.org/permalinks/wlog-10_e20170301-tg.htm) which I assume you know, but, if not, suggest to read. The [list of free licences](http://www.mirbsd.org/FreeLicenceLists.htm#lists) on my website is new, created after that article.

**Comment by nsqe** [comment]
@mirabilos  — again, as I mentioned in my comment in https://github.com/github/site-policy/issues/7, we really appreciate this review. 

> One thing I noticed in the post-pull#1 wording is that it only applies to “Your Content”, which is defined as content that the person uploading it to GitHub creates or owns. Is this deliberate?

Yes, this is deliberate, and was added specifically to address some of the same concerns you mentioned back in March. We want to differentiate content that the user creates or owns from content that the user is uploading that was created by others and is licensed.

If the user creates content on GitHub or is uploading content he or she owns, the user can grant us the permission we require regardless of the license the user has applied to the content. If the user is uploading content created by others that is licensed, the section on Moral Rights does not apply.

So again, I believe the changes we have made address your concerns. As with https://github.com/github/site-policy/issues/7, I'm interested in any comments the rest of the community has, so I'll leave this open for discussion.

**Comment by mirabilos** [comment]
Hi Hannah,

>@mirabilos  — again, as I mentioned in my comment in
>@https://github.com/github/site-policy/issues/7, we really appreciate
>@this review.

thanks.

>> One thing I noticed in the post-pull#1 wording is that it only
>> applies to “Your Content”, which is defined as content that the
>> person uploading it to GitHub creates or owns. Is this deliberate?
>
>Yes, this is deliberate, and was added specifically to address some of
>the same concerns you mentioned back in March. We want to

OK, I’ll see about that, but it may just suffice for this issue.

I’ll have to reread the two entire issue threads and check with
the information you have given me (thanks!) and will write again,
I just haven’t got the time to do so and had taken ill for today,
but I’ll look at this once I get enough time to do it properly.

Thanks!

**Comment by mirabilos** [comment]
> If the user is uploading content created by others that is licensed, the section on Moral Rights does not apply.

That’s good enough for me, I consider this specific issue closed with that update.

**Comment by wking** [comment]
On Fri, Jul 7, 2017 at 03:03:37PM -0700, nsqe wrote:
> We want to differentiate content that the user creates or owns from
> content that the user is uploading that was created by others and is
> licensed.
> …
> If the user is uploading content created by others that is licensed,
> the section on Moral Rights does not apply.

Why do you want to differentiate?  Say Alice creates a work and
publishes it with an open license to a Git repository hosted on her
website.  Then Bob clones Alice's work and uploads it to a GitHub
repository (so he doesn't have the copyright or moral rights).  Carol
creates a separate work under the same license and uploads it to
GitHub directly.  Alice's license grant for the rights in §D.4 [1]
(and fair-use, etc.) is sufficient to allow indexing and displaying
search results, etc. for Bob's repository (especially if you're always
linking back from the excerpt to the source repo).  If it wasn't, you
couldn't host things like [2] on GitHub.  So why would you need Carol
to waive any moral rights to index and display search results,
etc. for her repository?  Isn't her license sufficient, just like
Alice's license was sufficient?

[1]: https://github.com/github/site-policy/blob/75c016d80fe819c192f5c953eb3829bee63462a2/Policies/github-terms-of-service.md#4-license-grant-to-us
[2]: https://github.com/torvalds/linux

**Comment by mirabilos** [comment]
W. Trevor King dixit:

>So why would you need Carol to waive any moral rights to index and
>display search results, etc. for her repository? Isn't her license
>sufficient, just like Alice's license was sufficient?

Ask the GitHub people… I’m surprised as well, but as long as the
ToS don’t require Bob to grant the waiver (which they cannot) or
Alice (who doesn’t upload this content to GitHub so is out of the
tailor) I’m fine, from a point-of-view matching my generic review
of the ToS and their suitability for Free/OSS projects.
