### ISSUE TITLE
Reporting typos in doc: "Building a CLI with a GitHub App"

### ISSUE THREAD

**Issue by GruntySoftware** [github/site-policy#811]
Reporting typos in doc: "Building a CLI with a GitHub App"
https://docs.github.com/en/apps/creating-github-apps/writing-code-for-a-github-app/building-a-cli-with-a-github-app

· Section "Add a help command", step (3)
Reads: "The order of the functions don't matter"
Should read: "The order of the functions do>es<n't matter"

· Section "Add a login command", step (2)
Missing "d" letter in:
"the function prints the response and body an>d< exits the program."

· Section "Add a login command", step (9)
Reads: "The order of the functions don't matter"
Should read: "The order of the functions do>es<n't matter"

· Section "Next steps", subsection "Securely store tokens"
Reads: "you may choose different way to store the token"
Should read: "you may choose different way>s< to store the token"

**Comment by Tovihujisodiq** [comment]
Sms-activate account verification

**Comment by jsoref** [comment]
This appears to be resolved by https://github.com/github/docs/pull/30938

**Comment by GruntySoftware** [comment]
Josh you're right. I've left my thanks there.
