### ISSUE TITLE
Link to github security article is broken.

### ISSUE THREAD

**Issue by kjusupov** [github/site-policy#82]
The link ["all reasonable and appropriate security measures"](https://github.com/github/site-policy/blob/master/articles/github-security) on "https://github.com/github/site-policy/blob/master/Policies/global-privacy-practices.md" is broken. Results in error 404.

Security
We will protect your personal information with all reasonable and appropriate security measures.

**Comment by bluemazzoo** [comment]
>This is probably intentional [1].  It may be worth mentioning (in CONTRIBUTING.md?) that /articles/… links will not resolve in GitHub's rendering of this content.

Thank you for the comments! @wking that is correct. Closing this issue, since the documents are intended to be copies of the public-facing documents on our [official site policy page](https://help.github.com/categories/site-policy/). I'll add a note to clarify this issue in the README.

**Comment by bluemazzoo** [comment]
The README has been updated to include a statement about the links in the documents.
