### ISSUE TITLE
Add a tag for the release prior to 2017-08-07

### ISSUE THREAD

**Issue by sschuberth** [github/site-policy#84]
Please add a tag for the release prior to 2017-08-07 so we can easily see the effective changes by running a diff on the tags.

**Comment by bluemazzoo** [comment]
Hi @sschuberth, thanks for this recommendation! We can definitely do that. I'll include a reply/link here and close out the issue, once the release tag has been created.

**Comment by bonebizz21** [comment]
Right on!

**Comment by anicha12** [comment]
![17157738_1349132031846239_3461866982310975249_o](https://user-images.githubusercontent.com/33065070/32136819-2654e074-bc3f-11e7-9452-1edcdf3e1c56.jpg)

**Comment by chookun** [comment]
แก้ไขปัญหาสองข้อที่มี

**Comment by bluemazzoo** [comment]
We were not able to add a release for the versions prior to 2017-08-07, but over the past year we have been adding releases around other substantive policy changes.

**Comment by vena2523** [comment]
ฉันได้แชร์รายการกับคุณ:

TrackView
https://drive.google.com/drive/folders/1su_n-reMDbM66zBY77kABWk8zMVCV4SI?usp=sharing&invite=CJbqs9wD&ts=5d900294

เอกสารนี้ไม่ใช่ไฟล์แนบ แต่จัดเก็บไว้ออนไลน์ หากต้องการเปิดดู  
ให้คลิกลิงก์ด้านบน
