### ISSUE TITLE
License button missing, why ?

### ISSUE THREAD

**Issue by mrcyberfighter** [github/site-policy#86]
#### Licensing.

Before their was a button to add a license file to the repository into the repository interface, which has disappear.

Is it because the License file into the repository has prior and it make messing the repository and so it is intentional.

Adding tags is a good idea for github.

**Comment by mlinksva** [comment]
@mrcyberfighter there's a button on the new repository page, see https://help.github.com/articles/licensing-a-repository/#applying-a-license-to-a-repository-with-an-existing-license and for existing repositories see https://help.github.com/articles/adding-a-license-to-a-repository/

Regarding tags, check out https://help.github.com/articles/classifying-your-repository-with-topics/

If you have other questions or suggestions I suggest contacting support at https://github.com/contact

Closing this as it isn't directly pertinent to GitHub's site policies.
