### ISSUE TITLE
Read me 

### ISSUE THREAD

**Issue by dnabookofficiaal** [github/site-policy#936]
**Please read our README.md and CONTRIBUTING.md files before creating an issue. If you are creating an issue to provide feedback about our Closed Policies, please note that we may not incorporate your feedback into our policies due to laws that limit our flexibility around those issues. If your feedback is not related to any of the questions below, feel free to delete the template questions and enter your comments in free form.**

#### 5. Why do you think this section or language needs improvement?

```[tasklist]
### Tasks
- [ ] https://github.com/github/site-policy/pull/930
- [x] #997
- [ ] https://github.com/github/site-policy/issues/934
```

```[tasklist]
### Tasks
```

**Comment by An010299** [comment]
> **Please read our README.md and CONTRIBUTING.md files before creating an issue. If you are creating an issue to provide feedback about our Closed Policies, please note that we may not incorporate your feedback into our policies due to laws that limit our flexibility around those issues. If your feedback is not related to any of the questions below, feel free to delete the template questions and enter your comments in free form.**
> 
> #### 1. What's the name of the policy?
> 
> #### 2. Is this issue related to a specific section within one of our policies (e.g. the Terms of Service)? If so, please include a link to the section or subsection.
> 
> #### 3. Did you already open a pull request? If so, please include a link to the PR in the [GitHub Docs repo](https://github.com/github/docs).
> 
> #### 4. Sometimes it's easier to just put your feedback text into an issue. If that's how you'd prefer to contribute, this is the section to do that.
> 
> #### 5. Why do you think this section or language needs improvement?
> 
> ```[tasklist]
> ### Tasks
> - [ ] https://github.com/github/site-policy/pull/930
> - [x] #997
> - [ ] https://github.com/github/site-policy/issues/934
> ```
> 
> ```[tasklist]
> ### Tasks
> ```
> 

> Olá, realmente não acompanhei esse processo de contribuição < No projeto ou na investigação > .

> Entrei aqui há quatro anos tentando provar o plágio e não consegui. Em seguida me afastei.

> Não tenho a habilidade de programadores profissionais, sinalizei pela linguagem mais simples .

> Qual a sua especialidade? De linguagem?

> Aprovar sua contribuição, te beneficia em quê?

> Você entende de hermenêutica jurídica?

> Me chame de voz
