### ISSUE TITLE
Want to translate policies folder

### ISSUE THREAD

**Issue by anaufalm** [github/site-policy#96]
Hello team github,
I am indonesian translator, I want to help translate this document into indonesian language to facilitate users from Indonesia to understand the contents of existing documents in the policies folder.

If allowed, I will create new folder name: `id_ID_policies` in my repo and will merge to master. And  I will be happy to start translate all of document in policies folder.
Thank you for your attention, :)

Regard

**Comment by lee-dohm** [comment]
Thanks very much for the offer!

Unfortunately, we're not prepared to have translations of our site policies at this point in time. This still is a longer-term goal for us, though there are a number of challenging issues to tackle first. We'll do our best to communicate when we're ready for the next step here.
